import i18n from '../i18n';
import type { SystemSettings } from '../contexts/SettingsContext';
import { localDb, transactionLocalService } from '../lib/localDatabase';
import { connectionStatus, supabase } from '../lib/supabase';
import type { LocalCustomer } from '../types/supabase';
import { generateUUID } from '../utils/uuid';
import { asUnresolvedIssueFailure, FiscalBackendUnavailableError } from './fiscalFailure';
import type {
    ExternalFiscalSnapshot,
    ExternalIssuedItemReference,
    FiscalCheckoutResult,
} from './types';
import {
    buildSaleCheckoutDraft,
    type FiscalCartLine,
    type FiscalGlobalDiscount,
    type FiscalPaymentInput,
} from './saleCheckoutDraft';
import type { SaftFiscalDocumentType } from './spec';

/**
 * Fiskaly SIGN PT fiscal issuer — SIGN PT is the Portugal service of fiskaly's
 * UNIFIED API (test/live.api.fiskaly.com), not a specialized per-country API.
 * We proxy through the `fiskaly-fiscal` edge function (which holds the API
 * key/secret and runs the verified INTENTION -> TRANSACTION record flow) and
 * persist an immutable snapshot.
 *
 * Contract verified 2026-07-19 against the official SIGN PT OpenAPI 2026-06-01
 * (REGISTER B16, docs/fiskaly-pt-contract-capture.md). Key corrections vs the
 * pre-rewrite assumptions: document numbers/series are generated by US (the
 * taxpayer), never by fiskaly; all money values are decimal STRINGS; the response
 * carries ATCUD at compliance.data, the QR payload at compliance.qr_code and the
 * printed 4-char hash at compliance.signature_hash.
 * ⚠️ RUNTIME-UNVERIFIED: SIGN PT is not enabled on our fiskaly org, so no
 * authenticated issuance has ever run; the VAT-rate code mapping below and the
 * cent-rounding tolerance are open questions for the first live TEST pass.
 * ⚠️ NUMBERING DURABILITY: correlative numbers are derived from the local Dexie
 * chain tip (single-till assumption, same as local_at). A wiped browser profile or
 * a second till sharing the same systemId/series would restart/collide the series —
 * multi-till PT fiskaly issuance must go through pos-checkout (server-allocated
 * numbers), never this path. See capture doc §6.
 * fiskaly claims AT certification but publishes no certificate number (B5/B14) —
 * `local_at` remains the Portugal primary issuer until that is verified.
 */

const EDGE_FUNCTION = 'fiskaly-fiscal';

/** Record content returned by the edge function (spec: RecordResource.content). */
interface FiskalyRecordContent {
    id?: string;
    state?: string;
    mode?: string;
    journal?: { signature?: string; signed_at?: string };
    compliance?: {
        data?: string;
        qr_code?: string;
        signature_hash?: string;
        software_certificate?: string;
        url?: string;
        sequence?: { number?: number; signature?: string; type?: string };
    };
    logs?: unknown;
    [key: string]: unknown;
}

interface FiskalyFunctionResponse {
    record?: FiskalyRecordContent;
    status?: 'completed' | 'processing';
    zip_base64?: string;
    artifact_type?: string;
    file?: Record<string, unknown>;
    ok?: boolean;
    organization?: unknown;
    system?: unknown;
    error?: string;
}

function assertFiskalyEnabled(settings: SystemSettings): void {
    if (settings.fiscal.issuer !== 'fiskaly' || !settings.fiscal.fiskaly.enabled) {
        throw new Error(i18n.t('checkout.fiskalyNotEnabled'));
    }
    const f = settings.fiscal.fiskaly;
    if (!f.taxpayerId.trim() || !f.locationId.trim() || !f.systemId.trim()) {
        throw new Error(i18n.t('checkout.fiskalyMissingIds'));
    }
}

// Runs before the issue-attempt row is created, so a throw here is the one
// failure that provably left no trace at fiskaly (see fiscalFailure.ts).
function assertOnline(): void {
    const state = connectionStatus.getStatus();
    if (!state.isOnline || !state.isSupabaseOnline) {
        throw new FiscalBackendUnavailableError('fiskaly', i18n.t('checkout.fiskalyOffline'));
    }
}

function certificationMode(settings: SystemSettings): 'production' | 'training' {
    return settings.fiscal.trainingMode || settings.fiscal.fiskaly.environment === 'test' ? 'training' : 'production';
}

/** All fiskaly money/quantity values are decimal STRINGS (spec Decimal12p8). */
function money(n: number): string {
    return n.toFixed(2);
}

/**
 * ⚠️ ASSUMED (runtime-unverified): PT mainland VAT-rate -> SystemVatRateCode mapping.
 * The authoritative per-region table lives in fiskaly's support article
 * "SIGN PT VAT rates" and must be confirmed on the first live TEST pass.
 */
const VAT_RATE_CODES: Record<string, string> = {
    '23': 'STANDARD',
    '13': 'REDUCED_1',
    '6': 'REDUCED_2',
};

function vatCodeForRate(pct: number): string {
    const code = VAT_RATE_CODES[String(pct)];
    if (!code) {
        throw new Error(i18n.t('checkout.fiskalyVatRateUnmapped', { pct }));
    }
    return code;
}

/** `iva_rate` is stored as a FRACTION (0.23 = 23%) — same convention as exportSaft. */
function ratePercent(ivaRate: number): number {
    return Math.round(ivaRate * 10000) / 100;
}

/** Exemption codes must already be fiskaly enum values (NOT_SUBJECT/NOT_TAXABLE/CAUSE_n). */
function exemptionCode(settings: SystemSettings): string {
    const code = settings.fiscal.fiskaly.exemptTax.code?.trim().toUpperCase() ?? '';
    if (!/^(NOT_SUBJECT|NOT_TAXABLE|CAUSE_\d{1,2})$/.test(code)) {
        throw new Error(i18n.t('checkout.fiskalyExemptionCodeInvalid', { code: code || '—' }));
    }
    return code;
}

/** DocumentIdentifier: ^[0-9A-Z_/\-\.]{1,20}$ — sanitize a label into that charset. */
function sanitizeSeriesLabel(label: string): string {
    return label.trim().toUpperCase().replace(/[^0-9A-Z_.-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 12);
}

type Draft = ReturnType<typeof buildSaleCheckoutDraft>;

/**
 * Per-line money normalized ONCE to integer cents, so entries, breakdown and totals
 * are consistent with each other by construction (fiskaly's cross-sum tolerance is
 * runtime-unverified — capture doc §6).
 */
interface LineCents {
    pct: number;
    inclusiveC: number;
    taxC: number;
    exclusiveC: number;
    discountExclC: number;
}

function lineCentsFor(item: Draft['transactionItems'][number]): LineCents {
    const inclusiveC = Math.round(item.line_total * 100);
    const taxC = Math.round(item.tax_amount * 100);
    return {
        pct: ratePercent(item.iva_rate),
        inclusiveC,
        taxC,
        exclusiveC: inclusiveC - taxC,
        // draft discount_amount is VAT-inclusive; fiskaly entry values are VAT-exclusive
        discountExclC: Math.round(((item.discount_amount || 0) / (1 + item.iva_rate)) * 100),
    };
}

function centsToMoney(c: number): string {
    return (c / 100).toFixed(2);
}

function buildEntries(settings: SystemSettings, draft: Draft): Array<Record<string, unknown>> {
    return draft.transactionItems.map(item => {
        const c = lineCentsFor(item);
        const unitInclusive = item.unit_price;
        const unitExclusive = Number((unitInclusive / (1 + item.iva_rate)).toFixed(2));
        const vat = c.pct > 0
            ? {
                type: 'VAT_RATE',
                code: vatCodeForRate(c.pct),
                percentage: c.pct.toFixed(1),
                amount: centsToMoney(c.taxC),
                exclusive: centsToMoney(c.exclusiveC),
                inclusive: centsToMoney(c.inclusiveC),
            }
            : {
                type: 'VAT_EXEMPTION',
                code: exemptionCode(settings),
                ...(settings.fiscal.fiskaly.exemptTax.law?.trim()
                    ? { reason: settings.fiscal.fiskaly.exemptTax.law.trim().slice(0, 128) }
                    : {}),
            };
        return {
            type: 'SALE',
            data: {
                type: 'ITEM',
                text: (item.product_name || 'Artigo').slice(0, 256),
                unit: {
                    quantity: String(item.quantity),
                    // unit price is PRE-discount; the line discount is declared in value.discount
                    price: { inclusive: money(unitInclusive), exclusive: money(unitExclusive) },
                },
                // base = line amount excluding VAT, net of the line discount.
                // ⚠️ value.discount semantics (incl/excl VAT) are runtime-unverified — we send
                // the VAT-exclusive amount so qty×price.exclusive − discount ≈ base (§6).
                value: {
                    base: centsToMoney(c.exclusiveC),
                    ...(c.discountExclC > 0 ? { discount: centsToMoney(c.discountExclC) } : {}),
                },
                vat,
                // Product is a discriminated oneOf — SKU variant requires type+number+details.name
                ...(item.product_sku
                    ? {
                        product: {
                            type: 'SKU',
                            number: String(item.product_sku).slice(0, 128),
                            details: { name: (item.product_name || 'Artigo').slice(0, 256) },
                        },
                    }
                    : {}),
            },
            details: { concept: 'GOOD' },
        };
    });
}

function buildBreakdown(settings: SystemSettings, draft: Draft): Array<Record<string, unknown>> {
    const byRate = new Map<number, { taxC: number; exclusiveC: number; inclusiveC: number }>();
    for (const item of draft.transactionItems) {
        const c = lineCentsFor(item);
        const agg = byRate.get(c.pct) ?? { taxC: 0, exclusiveC: 0, inclusiveC: 0 };
        agg.taxC += c.taxC;
        agg.inclusiveC += c.inclusiveC;
        agg.exclusiveC += c.exclusiveC;
        byRate.set(c.pct, agg);
    }
    return Array.from(byRate.entries()).map(([pct, agg]) =>
        pct > 0
            ? {
                type: 'VAT_RATE',
                code: vatCodeForRate(pct),
                percentage: pct.toFixed(1),
                amount: centsToMoney(agg.taxC),
                exclusive: centsToMoney(agg.exclusiveC),
                inclusive: centsToMoney(agg.inclusiveC),
            }
            : {
                type: 'VAT_EXEMPTION',
                code: exemptionCode(settings),
                exclusive: centsToMoney(agg.exclusiveC),
            }
    );
}

function buildTotals(draft: Draft): Record<string, unknown> {
    let taxC = 0;
    let inclusiveC = 0;
    for (const item of draft.transactionItems) {
        const c = lineCentsFor(item);
        taxC += c.taxC;
        inclusiveC += c.inclusiveC;
    }
    return { vat: { amount: centsToMoney(taxC), exclusive: centsToMoney(inclusiveC - taxC), inclusive: centsToMoney(inclusiveC) } };
}

function buildPayments(draft: Draft, payment: FiscalPaymentInput): Array<Record<string, unknown>> {
    const amount = money(draft.total);
    // ⚠️ Card payments go out as OTHER("CARD"): the spec's CARD type requires a masked
    // PAN + kind, which an external terminal never gives the POS. Open question for
    // fiskaly (SAF-T PaymentMechanism impact) — see docs/fiskaly-pt-contract-capture.md.
    if (payment.paymentMethod === 'cash') {
        return [{ type: 'CASH', details: { amount } }];
    }
    return [{ type: 'OTHER', name: payment.paymentMethod === 'card' ? 'CARD' : 'MIXED', details: { amount } }];
}

function buildRecipients(customer: LocalCustomer | null): Array<Record<string, unknown>> {
    // INVOICE (FT) requires a full spec-shaped recipient. We can only build a
    // BUSINESS recipient (LegalName + Address + VAT id); a CONSUMER recipient needs
    // gender/forename/surname which the POS does not capture.
    if (!customer) {
        throw new Error(i18n.t('checkout.fiskalyInvoiceNeedsCustomer'));
    }
    const nif = customer.tax_number?.replace(/\s/g, '').trim();
    const line = customer.address?.trim();
    const code = customer.postal_code?.trim();
    const city = customer.city?.trim();
    if (!nif || !customer.name?.trim() || !line || !code || !city) {
        throw new Error(i18n.t('checkout.fiskalyInvoiceNeedsCustomerFields'));
    }
    // Address.line is a discriminated OBJECT (only variant STREET_NUMBER, requiring
    // street + number) — a plain string is schema-rejected. Our customer record has a
    // single free-text line, so split heuristically: trailing token starting with a
    // digit = door number; otherwise "S/N" (sem número). ⚠️ Runtime-unverified (§6).
    const lineMatch = line.match(/^(.*?)[,\s]+(\d[\w\-/º°.]*)$/);
    const street = (lineMatch ? lineMatch[1] : line).trim().slice(0, 128) || line.slice(0, 128);
    const doorNumber = (lineMatch ? lineMatch[2] : 'S/N').slice(0, 128);
    return [{
        type: 'BUSINESS',
        name: customer.name.trim().slice(0, 128),
        address: {
            line: { type: 'STREET_NUMBER', street, number: doorNumber },
            code,
            city,
            country: (customer.country || 'PT').trim().slice(0, 2).toUpperCase() || 'PT',
        },
        identification: { type: 'VAT', number: nif },
    }];
}

function externalItemRefs(localItems: Draft['transactionItems']): ExternalIssuedItemReference[] {
    // The record response carries no per-line ids (operation echo is opaque JsonData).
    return localItems.map((item, index) => ({
        localProductId: item.product_id,
        localSku: item.product_sku,
        externalItemId: null,
        referenceId: null,
        documentRow: index + 1,
    }));
}

async function invokeFunction(body: Record<string, unknown>): Promise<FiskalyFunctionResponse> {
    const { data, error } = await supabase.functions.invoke<FiskalyFunctionResponse>(EDGE_FUNCTION, { body });
    if (error) {
        throw new Error(i18n.t('checkout.fiskalyEdgeFunctionFailed', { error: error.message }));
    }
    if (!data) {
        throw new Error(i18n.t('checkout.fiskalyEdgeFunctionNoData'));
    }
    if (data.error) {
        throw new Error(data.error);
    }
    return data;
}

function snapshotFrom(
    record: FiskalyRecordContent,
    params: {
        settings: SystemSettings;
        type: SaftFiscalDocumentType;
        txId: string;
        externalReference: string;
        documentNumber: string;
        seriesLabel: string;
        chainScope: string;
        amountGross: number;
        amountNet: number;
        transactionDate: string;
        systemEntryDate: string;
        items: ExternalIssuedItemReference[];
    }
): ExternalFiscalSnapshot {
    const id = record.id == null ? '' : String(record.id);
    if (!id) {
        throw new Error(i18n.t('checkout.fiskalyRecordNoId'));
    }
    if (record.state === 'REJECTED' || record.state === 'FAILED') {
        throw new Error(i18n.t('checkout.fiskalyRecordRejected', {
            state: record.state,
            logs: JSON.stringify(record.logs ?? null),
        }));
    }
    const atcud = record.compliance?.data?.trim() || '';
    const signatureHash = record.compliance?.signature_hash?.trim() || '';
    const qrData = record.compliance?.qr_code || '';
    if (!atcud || !signatureHash || !qrData) {
        // A PT sale document cannot be lawfully printed without ATCUD, QR payload and
        // the 4-char signature hash. The record may already exist at fiskaly — the
        // attempt ledger keeps id+response, and an identical retry reuses the same
        // checkoutId (see issueFiskalySale), so fiskaly replays the record instead of
        // double-issuing.
        throw new Error(i18n.t('checkout.fiskalyRecordIncomplete', {
            atcud: atcud || '—',
            hash: signatureHash || '—',
            qr: qrData ? 'ok' : '—',
            state: record.state ?? '?',
            mode: record.mode ?? '?',
        }));
    }
    const f = params.settings.fiscal.fiskaly;
    const signedAt = record.journal?.signed_at?.trim();
    return {
        provider: 'fiskaly',
        documentId: id,
        number: params.documentNumber,
        type: params.type,
        date: signedAt ? signedAt.slice(0, 10) : params.transactionDate,
        systemTime: signedAt || params.systemEntryDate,
        localTime: signedAt || params.systemEntryDate,
        amountGross: params.amountGross,
        amountNet: params.amountNet,
        // printed 4-char hash element (guarded non-empty above); the full chain
        // signature stays in `raw`/providerMeta — never printed as the hash chars
        hash: signatureHash,
        atcud,
        qrcodeData: qrData,
        outputFormat: 'none',
        output: undefined,
        outputData: undefined,
        txId: params.txId,
        externalReference: params.externalReference,
        chainScope: params.chainScope,
        atValidationCode: atcud.split('-')[0] || 'FISKALY',
        items: params.items,
        providerMeta: {
            environment: f.environment,
            taxpayerId: f.taxpayerId.trim(),
            locationId: f.locationId.trim(),
            systemId: f.systemId.trim(),
            seriesLabel: params.seriesLabel,
            recordState: record.state,
            recordMode: record.mode,
            journalSignature: record.journal?.signature,
            softwareCertificate: record.compliance?.software_certificate,
        },
        raw: record,
    };
}

export async function issueFiskalySale(params: {
    settings: SystemSettings;
    cart: FiscalCartLine[];
    selectedCustomer: LocalCustomer | null;
    payment: FiscalPaymentInput;
    globalDiscount?: FiscalGlobalDiscount;
}): Promise<FiscalCheckoutResult> {
    const { settings, cart, selectedCustomer, payment, globalDiscount } = params;
    assertFiskalyEnabled(settings);
    assertOnline();

    // ⚠️ Global discounts are NOT distributed into the draft's per-line values, so a
    // record built from the lines would overstate revenue/VAT vs the charged total.
    // Loudly blocked until the first live TEST pass settles discount representation (§6).
    if (globalDiscount && globalDiscount.type !== 'none' && (globalDiscount.value > 0 || globalDiscount.amount > 0)) {
        throw new Error(i18n.t('checkout.fiskalyGlobalDiscountUnsupported'));
    }

    const f = settings.fiscal.fiskaly;
    const draft = buildSaleCheckoutDraft({ cart, selectedCustomer, payment, globalDiscount });
    const type = f.documentType;
    const amountGross = Number(draft.total.toFixed(2));
    const amountNet = Number((draft.total - draft.totalTax).toFixed(2));

    const nif = selectedCustomer?.tax_number?.replace(/\s/g, '').trim() || '';
    const common = {
        entries: buildEntries(settings, draft),
        payments: buildPayments(draft, payment),
        breakdown: buildBreakdown(settings, draft),
        totals: buildTotals(draft),
    };
    // RECEIPT covers FR (simplified_invoice=false) and FS (true); INVOICE covers FT.
    // A NIF on a receipt travels as customer.code — it never upgrades the doc type.
    const buildOperation = (documentNumber: string): Record<string, unknown> => type === 'FT'
        ? {
            type: 'INVOICE',
            document: { number: documentNumber, series: seriesLabel },
            recipients: buildRecipients(selectedCustomer),
            ...common,
        }
        : {
            type: 'RECEIPT',
            document: { number: documentNumber, series: seriesLabel, simplified_invoice: type === 'FS' },
            ...(nif ? { customer: { type: 'EXTERNAL', code: nif.slice(0, 128) } } : {}),
            ...common,
        };
    const cashierLabel = payment.employeeName || payment.employeeNumber || 'cashier';
    const training = settings.fiscal.trainingMode;

    // ---- document number: generated by US (spec: taxpayer-generated, correlative) ----
    const year = new Date().getFullYear();
    const envTag = f.environment === 'test' ? 'T' : 'L';
    const seriesLabel = sanitizeSeriesLabel(f.seriesId || '') || `${type}-${envTag}01-${year}`;
    const chainScope = `fiskaly::${f.environment}::${f.systemId.trim()}::${type}::${seriesLabel}`;
    const last = await transactionLocalService.getLastFiscalDocumentInChain(chainScope);

    // Retry convergence: an open (non-persisted) attempt may already hold the number we
    // are about to allocate, and its record may EXIST at fiskaly even though nothing was
    // persisted locally (lost response / record incomplete at read time). Re-running the
    // IDENTICAL sale reuses that attempt's checkoutId, so the edge fn's derived
    // X-Idempotency-Keys make fiskaly replay the original records instead of signing a
    // duplicate with the same correlative number. A DIFFERENT sale skips the
    // possibly-burned number — a series gap is explainable, a duplicate number is not (§6).
    const openAttempts = (await localDb.vendusIssueAttempts.toArray())
        .filter(a => a.provider === 'fiskaly' && a.status !== 'persisted');
    const requestOf = (json: string | null): Record<string, unknown> | null => {
        try { return JSON.parse(json ?? 'null'); } catch { return null; }
    };
    const identityOf = (r: Record<string, unknown> | null): string => JSON.stringify({
        e: r?.environment, s: r?.systemId, c: r?.cashierLabel, t: r?.training, o: r?.operation,
    });
    let sequential = (last?.sequential_number ?? 0) + 1;
    let attemptId = generateUUID();
    let reusedAttempt = false;
    let documentNumber = `${seriesLabel}/${sequential}`;
    let operation = buildOperation(documentNumber);
    for (;;) {
        const clash = openAttempts.find(a => {
            const r = requestOf(a.request_json);
            return (r?.operation as { document?: { number?: string } } | undefined)?.document?.number === documentNumber
                && r?.environment === f.environment && r?.systemId === f.systemId.trim();
        });
        if (!clash) break;
        const clashRequest = requestOf(clash.request_json);
        if (identityOf(clashRequest) === identityOf({ environment: f.environment, systemId: f.systemId.trim(), cashierLabel, training, operation })) {
            attemptId = clash.id;
            reusedAttempt = true;
            break;
        }
        sequential += 1;
        documentNumber = `${seriesLabel}/${sequential}`;
        operation = buildOperation(documentNumber);
    }
    if (documentNumber.length > 20) {
        throw new Error(i18n.t('checkout.fiskalyDocumentNumberTooLong', { number: documentNumber }));
    }
    const txId = `pos-sale-${attemptId}`;
    const externalReference = `POS-${attemptId}`;

    const request = {
        action: 'issue_document' as const,
        environment: f.environment,
        systemId: f.systemId.trim(),
        checkoutId: attemptId,
        cashierLabel,
        training,
        operation,
    };

    if (reusedAttempt) {
        await transactionLocalService.updateVendusIssueAttempt(attemptId, {
            status: 'pending',
            error_message: null,
        });
    } else {
        await transactionLocalService.createVendusIssueAttempt({
            id: attemptId,
            provider: 'fiskaly',
            kind: 'sale',
            tx_id: txId,
            external_reference: externalReference,
            status: 'pending',
            vendus_document_id: null,
            local_transaction_id: null,
            request_json: JSON.stringify(request),
            response_json: null,
            error_message: null,
        });
    }

    try {
        const response = await invokeFunction(request);
        if (!response.record) {
            throw new Error(i18n.t('checkout.fiskalyNoRecord'));
        }
        const external = snapshotFrom(response.record, {
            settings,
            type,
            txId,
            externalReference,
            documentNumber,
            seriesLabel,
            chainScope,
            amountGross,
            amountNet,
            transactionDate: draft.transactionDate,
            systemEntryDate: draft.systemEntryDate,
            items: externalItemRefs(draft.transactionItems),
        });
        await transactionLocalService.updateVendusIssueAttempt(attemptId, {
            status: 'issued',
            vendus_document_id: external.documentId,
            response_json: JSON.stringify(response.record),
        });
        const result = await transactionLocalService.createExternalFiscalCheckoutAtomic({
            certificationMode: certificationMode(settings),
            transactionDate: draft.transactionDate,
            transactionTime: draft.transactionTime,
            systemEntryDate: draft.systemEntryDate,
            grossTotal: draft.total,
            netRounded: amountNet,
            taxTotal: draft.totalTax,
            totalDiscountAmount: draft.totalDiscountAmount,
            originalSubtotal: draft.originalSubtotal,
            total: draft.total,
            changeGiven: draft.changeGiven,
            transactionBase: draft.transactionBase,
            transactionItems: draft.transactionItems,
            customerTaxId: draft.fiscalCustomer.taxIdForFiscalRow,
            payment,
            external,
        });
        await transactionLocalService.updateVendusIssueAttempt(attemptId, {
            status: 'persisted',
            vendus_document_id: external.documentId,
            local_transaction_id: result.transactionId,
        });
        return result;
    } catch (error) {
        await transactionLocalService.updateVendusIssueAttempt(attemptId, {
            status: 'failed',
            error_message: error instanceof Error ? error.message : String(error),
        });
        // Past the network call: the correlative number is burned and fiskaly may
        // hold a record for it. The attempt row above is what a retry converges
        // on; a paper invoice on top of that would double-invoice the sale.
        throw asUnresolvedIssueFailure(error, {
            provider: 'fiskaly',
            externalReference,
            attemptId,
        });
    }
}

export async function issueFiskalyCreditNoteForTransaction(params: {
    settings: SystemSettings;
    originalTransactionId: string;
    payment: FiscalPaymentInput;
    creditReason?: string;
}): Promise<FiscalCheckoutResult> {
    throw new Error(
        i18n.t('checkout.fiskalyCreditNotesUnavailable', { transactionId: params.originalTransactionId })
    );
}

/**
 * SAF-T (PT) via the unified API: POST /files {type:"AUDIT", range} then stream the
 * zip artifact. The range must cover an already-ended month (spec constraint).
 * Returns the raw ZIP bytes — the artifact is an archive, not bare XML.
 */
export async function fetchFiskalySaftArchive(params: {
    settings: SystemSettings;
    year: number;
    month: number;
}): Promise<{ bytes: Uint8Array; mimeType: string }> {
    assertFiskalyEnabled(params.settings);
    assertOnline();
    const f = params.settings.fiscal.fiskaly;
    const from = `${params.year}-${String(params.month).padStart(2, '0')}-01`;
    const lastDay = new Date(params.year, params.month, 0).getDate();
    const to = `${params.year}-${String(params.month).padStart(2, '0')}-${String(lastDay).padStart(2, '0')}`;
    const response = await invokeFunction({
        action: 'saft',
        environment: f.environment,
        taxpayerId: f.taxpayerId.trim(),
        from,
        to,
    });
    if (response.status === 'processing') {
        throw new Error(i18n.t('checkout.fiskalySaftProcessing'));
    }
    if (!response.zip_base64) {
        throw new Error(i18n.t('checkout.fiskalySaftMissing'));
    }
    const binary = atob(response.zip_base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return { bytes, mimeType: response.artifact_type || 'application/zip' };
}

export interface FiskalyHealthCheckResult {
    ok: boolean;
    organization: unknown;
    system: unknown;
}

export async function checkFiskalyFiscalHealth(settings: SystemSettings): Promise<FiskalyHealthCheckResult> {
    assertFiskalyEnabled(settings);
    assertOnline();
    const f = settings.fiscal.fiskaly;
    const response = await invokeFunction({
        action: 'health_check',
        environment: f.environment,
        taxpayerId: f.taxpayerId.trim(),
        systemId: f.systemId.trim(),
    });
    return {
        ok: Boolean(response.ok),
        organization: response.organization,
        system: response.system,
    };
}
