import type { SpecimenInstance } from './buttonLabSpecimens';

/**
 * Real app usages per canonical specimen — GENERATED from the button audit
 * (2026-07-22). Variant assignment is heuristic (regex on the audit's
 * sourceComponent/style text; spot-checked against source). State twins
 * (active/inactive, on/off, selected/unselected) share one list — the same
 * call sites render both states. POS2 / DesignSystem v1 usages excluded
 * (files removed 2026-07-22). Regenerate rather than hand-editing.
 */

export const CANONICAL_INSTANCES: Record<string, SpecimenInstance[]> = {
    "action-button-outline": [
        { label: "Outline", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Outline (ActionButton)" },
    ],
    "action-button-primary": [
        { label: "Create/Update employee", ref: "src/pages/Employees.tsx", note: "Create/Update employee (desktop dialog footer submit)" },
        { label: "Print || 'Print')", ref: "src/components/ReceiptDialog.tsx", note: "Print (t('common.print') || 'Print')" },
        { label: "Footer - Keyboard toggle", ref: "src/components/ProductForm.tsx", note: "Footer \u2014 Keyboard toggle" },
        { label: "Footer - Update/Create/Saving subm", ref: "src/components/ProductForm.tsx", note: "Footer \u2014 Update/Create/Saving submit" },
        { label: "Apply (footer, t('pos.discountDial", ref: "src/components/DiscountDialog.tsx", note: "Apply (footer, t('pos.discountDialog.buttons.apply'))" },
        { label: "Select", ref: "src/components/CustomerDialog.tsx" },
        { label: "Save", ref: "src/components/CustomerDialog.tsx" },
        { label: "Add new customer", ref: "src/components/CustomerDialog.tsx", note: "Add new customer (empty-state CTA)" },
        { label: "Save/Update (isSubmitting ? t('cat", ref: "src/components/CategoryForm.tsx", note: "Save/Update (isSubmitting ? t('categories.form.saving') : category ? t('categories.form.update') : t('categories.form.cr" },
        { label: "Update / Create / Saving\u2026", ref: "src/components/CustomerForm.tsx", note: "Update / Create / Saving\u2026 (conditional)" },
        { label: "Process Transaction", ref: "src/components/OrderSummaryPanel.tsx", note: "Process Transaction (pos.processTransaction)" },
        { label: "Primary", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Primary (ActionButton)" },
        { label: "Disabled", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Disabled (ActionButton)" },
        { label: "Confirm Payment", ref: "src/components/PaymentDialog.tsx", note: "Confirm Payment (primary CTA)" },
    ],
    "action-button-secondary": [
        { label: "Cancel", ref: "src/pages/Employees.tsx", note: "Cancel (desktop Add/Edit-employee dialog footer)" },
        { label: "Cancel || 'Cancel')", ref: "src/components/ReceiptDialog.tsx", note: "Cancel (t('common.cancel') || 'Cancel')" },
        { label: "Footer - Cancel", ref: "src/components/ProductForm.tsx", note: "Footer \u2014 Cancel" },
        { label: "Cancel (footer, t('common.cancel')", ref: "src/components/DiscountDialog.tsx", note: "Cancel (footer, t('common.cancel'))" },
        { label: "Cancel", ref: "src/components/CustomerDialog.tsx", note: "Cancel (list view footer)" },
        { label: "Cancel", ref: "src/components/CategoryForm.tsx", note: "Cancel (t('categories.form.cancel'))" },
        { label: "Cancel", ref: "src/components/CustomerForm.tsx" },
        { label: "Reset to defaults", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Reset to defaults (t('designSystemPage.customizer.resetLabel'))" },
        { label: "Secondary", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Secondary (ActionButton)" },
    ],
    "admin-action-ghost": [
        { label: "Filters", ref: "src/pages/Employees.tsx", note: "Filters (desktop toolbar)" },
        { label: "Ghost", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Ghost (AdminActionButton)" },
        { label: "View Receipt", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "View Receipt (AdminActionButton, toolbar sample, ghost)" },
    ],
    "admin-action-icon": [
        { label: "Close customizer (X icon, aria-lab", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Close customizer (X icon, aria-label t('designSystemPage.customizer.closeAria'))" },
        { label: "Dismiss", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Dismiss (X icon, Toast x4 + Alert x5)" },
        { label: "Icon", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Icon (AdminActionButton, icon-only)" },
        { label: "Open menu", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Open menu (AdminActionButton, toolbar sample, icon-only)" },
    ],
    "admin-action-outline": [
        { label: "Custom Invoice", ref: "src/pages/Transactions.tsx", note: "Custom Invoice (t('transactions.customInvoice.button'))" },
        { label: "Filters", ref: "src/pages/Transactions.tsx", note: "Filters (t('transactions.filters.filters'))" },
        { label: "Refresh", ref: "src/pages/Transactions.tsx", note: "Refresh (t('transactions.refresh'))" },
        { label: "View Receipt", ref: "src/pages/Transactions.tsx", note: "View Receipt (t('transactions.list.viewReceipt'))" },
        { label: "Download", ref: "src/pages/Transactions.tsx", note: "Download (t('transactions.list.download'))" },
        { label: "Import Purchase", ref: "src/pages/Products.tsx", note: "Import Purchase (t('products.importPurchase'))" },
        { label: "Sort = 'Sort')", ref: "src/pages/Products.tsx", note: "Sort (t('products.header.sort') = 'Sort')" },
        { label: "Filter = 'Filter')", ref: "src/pages/Products.tsx", note: "Filter (t('products.header.filter') = 'Filter')" },
        { label: "t('deliveryOrders.header.sort') -", ref: "src/pages/DeliveryOrders.tsx", note: "t('deliveryOrders.header.sort') \u2014 Sort toolbar trigger" },
        { label: "t('deliveryOrders.header.filter')", ref: "src/pages/DeliveryOrders.tsx", note: "t('deliveryOrders.header.filter') \u2014 Filter toolbar trigger" },
        { label: "t('deliveryOrders.fiscal.downloadP", ref: "src/pages/DeliveryOrders.tsx", note: "t('deliveryOrders.fiscal.downloadPdf') \u2014 download PDF" },
        { label: "t('deliveryOrders.fiscal.openPlatf", ref: "src/pages/DeliveryOrders.tsx", note: "t('deliveryOrders.fiscal.openPlatform') \u2014 open platform (external link)" },
        { label: "Retry in error-state card", ref: "src/pages/ProfitCosts.tsx", note: "Retry (t('common.retry')) in error-state card" },
        { label: "Refresh - desktop toolbar", ref: "src/pages/ProfitCosts.tsx", note: "Refresh (t('profitCosts.header.refresh')) - desktop toolbar" },
        { label: "Reset - desktop toolbar", ref: "src/pages/ProfitCosts.tsx", note: "Reset (t('profitCosts.operatingCosts.reset')) - desktop toolbar" },
        { label: "Filters", ref: "src/pages/Reports.tsx", note: "Filters (desktop toolbar)" },
        { label: "Reset", ref: "src/pages/Appearances.tsx", note: "Reset (page header action)" },
        { label: "'Open View Modal' section trigger", ref: "src/components/DesignSystem2/ProductsPageReference2.tsx" },
        { label: "Sort toggle", ref: "src/pages/Customers.tsx" },
        { label: "Filter toggle", ref: "src/pages/Customers.tsx" },
        { label: "Button", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Button (Page Header row 1, 1st outline)" },
        { label: "Outline", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Outline (AdminActionButton)" },
        { label: "With chevron", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "With chevron (AdminActionButton)" },
        { label: "Filters", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Filters (AdminActionButton, toolbar sample, chevron)" },
        { label: "Rows per page", ref: "src/components/DesignSystem2/Table2.tsx", note: "Rows per page (\"10\")" },
    ],
    "admin-action-primary": [
        { label: "Add Employee", ref: "src/pages/Employees.tsx", note: "Add Employee (page header primary action)" },
        { label: "Export", ref: "src/pages/Transactions.tsx", note: "Export (t('transactions.header.export'))" },
        { label: "Segunda Via / reprint", ref: "src/pages/Transactions.tsx", note: "Segunda Via / reprint (t('thermalReceipt.secondCopy'))" },
        { label: "Issue Credit Note / issuing state)", ref: "src/pages/Transactions.tsx", note: "Issue Credit Note (t('transactions.list.issueCreditNote') / issuing state)" },
        { label: "Add Product = 'Add Product')", ref: "src/pages/Products.tsx", note: "Add Product (t('products.header.addProduct') = 'Add Product')" },
        { label: "Edit Product = 'Edit Product') - v", ref: "src/pages/Products.tsx", note: "Edit Product (t('products.viewModal.editProduct') = 'Edit Product') \u2014 view-modal footer, shared node used in both style " },
        { label: "Add - desktop toolbar", ref: "src/pages/ProfitCosts.tsx", note: "Add (t('profitCosts.operatingCosts.add')) - desktop toolbar" },
        { label: "Export to Excel / Exporting\u2026", ref: "src/pages/Reports.tsx", note: "Export to Excel / Exporting\u2026 (desktop toolbar)" },
        { label: "Retry loading employees button", ref: "src/components/Auth/LoginForm2.tsx", note: "Retry loading employees button (load-error screen)" },
        { label: "Toolbar 'Add Product' primary CTA", ref: "src/components/DesignSystem2/ProductsPageReference2.tsx" },
        { label: "View-modal footer 'Edit Product' C", ref: "src/components/DesignSystem2/ProductsPageReference2.tsx", note: "View-modal footer 'Edit Product' CTA" },
        { label: "Add customer", ref: "src/pages/Customers.tsx" },
        { label: "Edit customer", ref: "src/pages/Customers.tsx", note: "Edit customer (view-modal footer)" },
        { label: "Add Category", ref: "src/pages/Categories.tsx", note: "Add Category (header button)" },
        { label: "Open customizer FAB", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Open customizer FAB (t('designSystemPage.customizer.openLabel'))" },
        { label: "Primary", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Primary (AdminActionButton)" },
        { label: "Disabled", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Disabled (AdminActionButton, primary)" },
        { label: "Export", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Export (AdminActionButton, toolbar sample)" },
    ],
    "admin-action-success": [
        { label: "t('deliveryOrders.header.sync') -", ref: "src/pages/DeliveryOrders.tsx", note: "t('deliveryOrders.header.sync') \u2014 Sync button" },
        { label: "Button", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Button (Page Header row 1, primary/green override)" },
        { label: "Button 1", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Button 1 (Page Header row 2, primary/green override)" },
    ],
    "category-filter-selected": [
        { label: "t('pos.allMenu') - static 'All Men", ref: "src/pages/POS.tsx", note: "t('pos.allMenu') \u2014 static 'All Menu' category filter, always first in the sidebar list" },
        { label: "category.name - one CategoryFilter", ref: "src/pages/POS.tsx", note: "category.name \u2014 one CategoryFilterButton rendered per entry in allCategories (dynamic count, not translated)" },
        { label: "All Menu", ref: "src/components/DesignSystem2/Premade2.tsx" },
        { label: "Coffee", ref: "src/components/DesignSystem2/Premade2.tsx" },
        { label: "Beverages", ref: "src/components/DesignSystem2/Premade2.tsx" },
    ],
    "category-filter-unselected": [
        { label: "t('pos.allMenu') - static 'All Men", ref: "src/pages/POS.tsx", note: "t('pos.allMenu') \u2014 static 'All Menu' category filter, always first in the sidebar list" },
        { label: "category.name - one CategoryFilter", ref: "src/pages/POS.tsx", note: "category.name \u2014 one CategoryFilterButton rendered per entry in allCategories (dynamic count, not translated)" },
        { label: "All Menu", ref: "src/components/DesignSystem2/Premade2.tsx" },
        { label: "Coffee", ref: "src/components/DesignSystem2/Premade2.tsx" },
        { label: "Beverages", ref: "src/components/DesignSystem2/Premade2.tsx" },
    ],
    "dashed-card-button": [
        { label: "Add Category card (mobile grid) -", ref: "src/pages/Categories.tsx", note: "Add Category card (mobile grid) - t('categories.addCategoryCard')" },
        { label: "Add Category card (desktop grid) -", ref: "src/pages/Categories.tsx", note: "Add Category card (desktop grid) - t('categories.addCategoryCard')" },
        { label: "\"Add Category\"", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "\"Add Category\" (hardcoded demo label, DS2 showcase)" },
        { label: "'Add category' dashed card", ref: "src/pages/Categories.tsx", note: "'Add category' dashed card (mobile list)" },
        { label: "Add Category", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Add Category (DashedCardButton)" },
    ],
    "dialog-switch-off": [
        { label: "Sell-enabled status toggle row", ref: "src/pages/Inventory.tsx" },
        { label: "Active status toggle row", ref: "src/pages/Inventory.tsx" },
        { label: "Variant attribute enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Variant option enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Modifier enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Unlimited ingredients toggle", ref: "src/components/ProductWizard.tsx" },
    ],
    "dialog-switch-on": [
        { label: "Sell-enabled status toggle row", ref: "src/pages/Inventory.tsx" },
        { label: "Active status toggle row", ref: "src/pages/Inventory.tsx" },
        { label: "Variant attribute enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Variant option enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Modifier enabled toggle", ref: "src/components/ProductWizard.tsx" },
        { label: "Unlimited ingredients toggle", ref: "src/components/ProductWizard.tsx" },
    ],
    "dialog-toggle-row": [
        { label: "Product status (active/inactive) t", ref: "src/components/ProductWizard.tsx", note: "Product status (active/inactive) toggle" },
    ],
    "numpad-action": [
        { label: "(rotated Plus icon, NumpadButton a", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "(rotated Plus icon, NumpadButton action variant)" },
        { label: "Backspace/delete key", ref: "src/components/VirtualNumpad.tsx" },
    ],
    "numpad-confirm": [
        { label: "OK", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "OK (NumpadButton, confirm)" },
        { label: "Confirm", ref: "src/components/VirtualNumpad.tsx" },
        { label: "Page 1", ref: "src/components/DesignSystem2/Table2.tsx", note: "Page 1 (active/confirm variant)" },
    ],
    "numpad-default": [
        { label: "1", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "1 (NumpadButton, default)" },
        { label: "Digit keys", ref: "src/components/VirtualNumpad.tsx", note: "Digit keys (1-9, 0)" },
        { label: "Decimal separator key", ref: "src/components/VirtualNumpad.tsx", note: "Decimal separator key (locale-aware '.' or ',')" },
        { label: "Cancel", ref: "src/components/VirtualNumpad.tsx" },
        { label: "Pages 2\u20135", ref: "src/components/DesignSystem2/Table2.tsx", note: "Pages 2\u20135 (default variant)" },
    ],
    "outline-button": [
        { label: "Clear all order", ref: "src/components/OrderSummaryPanel.tsx", note: "Clear all order (pos.clearAllOrder)" },
        { label: "Clear all (outline)", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Clear all (outline) (OutlineButton)" },
    ],
    "pairing-primary": [
        { label: "Pair Device", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Pair Device (PairingButton, primary)" },
        { label: "Pair device", ref: "src/pages/DevicePairing.tsx", note: "Pair device (primary CTA)" },
    ],
    "pairing-secondary": [
        { label: "Scan QR", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Scan QR (PairingButton, secondary)" },
    ],
    "payment-method-selected": [
        { label: "Card payment-method selector", ref: "src/components/PaymentDialog.tsx", note: "Card payment-method selector (real usage)" },
        { label: "PaymentMethodButton catalog demo p", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "PaymentMethodButton catalog demo pair (cash/card)" },
        { label: "Cash (selected)", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Cash (selected) (PaymentMethodButton)" },
        { label: "Payment method: Cash", ref: "src/components/PaymentDialog.tsx" },
        { label: "Cash payment-method selector", ref: "src/components/PaymentDialog.tsx", note: "Cash payment-method selector (real usage)" },
        { label: "Card", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Card (PaymentMethodButton, unselected)" },
        { label: "Payment method: Card", ref: "src/components/PaymentDialog.tsx" },
    ],
    "payment-method-unselected": [
        { label: "Card payment-method selector", ref: "src/components/PaymentDialog.tsx", note: "Card payment-method selector (real usage)" },
        { label: "PaymentMethodButton catalog demo p", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "PaymentMethodButton catalog demo pair (cash/card)" },
        { label: "Cash (selected)", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Cash (selected) (PaymentMethodButton)" },
        { label: "Payment method: Cash", ref: "src/components/PaymentDialog.tsx" },
        { label: "Cash payment-method selector", ref: "src/components/PaymentDialog.tsx", note: "Cash payment-method selector (real usage)" },
        { label: "Card", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Card (PaymentMethodButton, unselected)" },
        { label: "Payment method: Card", ref: "src/components/PaymentDialog.tsx" },
    ],
    "pos-action-default": [
        { label: "Cash Drawer", ref: "src/components/OrderSummaryPanel.tsx", note: "Cash Drawer (pos.cashDrawer)" },
        { label: "Profile", ref: "src/components/OrderSummaryPanel.tsx", note: "Profile (common.profile)" },
        { label: "Tables", ref: "src/components/OrderSummaryPanel.tsx", note: "Tables (pos.tables, conditional)" },
        { label: "Customer", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Customer (POSActionButton)" },
        { label: "Discount", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Discount (POSActionButton)" },
        { label: "Save Bill", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Save Bill (POSActionButton, disabled)" },
    ],
    "pos-action-disabled": [
        { label: "Cash Drawer", ref: "src/components/OrderSummaryPanel.tsx", note: "Cash Drawer (pos.cashDrawer)" },
        { label: "Profile", ref: "src/components/OrderSummaryPanel.tsx", note: "Profile (common.profile)" },
        { label: "Tables", ref: "src/components/OrderSummaryPanel.tsx", note: "Tables (pos.tables, conditional)" },
        { label: "Customer", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Customer (POSActionButton)" },
        { label: "Discount", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Discount (POSActionButton)" },
        { label: "Save Bill", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Save Bill (POSActionButton, disabled)" },
    ],
    "product-card": [
        { label: "product.name - one ProductCard ren", ref: "src/pages/POS.tsx", note: "product.name \u2014 one ProductCard rendered per item in productsToShow (dynamic count, potentially dozens)" },
        { label: "Espresso", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Espresso (ProductCard)" },
        { label: "Cappuccino", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Cappuccino (ProductCard, in cart)" },
        { label: "Latte", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Latte (ProductCard, out of stock)" },
    ],
    "tab-button-reports-active": [
        { label: "Overview", ref: "src/pages/Reports.tsx", note: "Overview (desktop tab bar, 1 of 4)" },
        { label: "Employees", ref: "src/pages/Reports.tsx", note: "Employees (desktop tab bar, 2 of 4)" },
        { label: "Products", ref: "src/pages/Reports.tsx", note: "Products (desktop tab bar, 3 of 4)" },
        { label: "Inventory", ref: "src/pages/Reports.tsx", note: "Inventory (desktop tab bar, 4 of 4)" },
        { label: "Overview", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Overview (TabButton, reports, active)" },
        { label: "Employees", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Employees (TabButton, reports, inactive)" },
    ],
    "tab-button-reports-inactive": [
        { label: "Overview", ref: "src/pages/Reports.tsx", note: "Overview (desktop tab bar, 1 of 4)" },
        { label: "Employees", ref: "src/pages/Reports.tsx", note: "Employees (desktop tab bar, 2 of 4)" },
        { label: "Products", ref: "src/pages/Reports.tsx", note: "Products (desktop tab bar, 3 of 4)" },
        { label: "Inventory", ref: "src/pages/Reports.tsx", note: "Inventory (desktop tab bar, 4 of 4)" },
        { label: "Overview", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Overview (TabButton, reports, active)" },
        { label: "Employees", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Employees (TabButton, reports, inactive)" },
    ],
    "tab-button-sidebar-active": [
        { label: "Active", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Active (TabButton, sidebar)" },
        { label: "Inactive", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Inactive (TabButton, sidebar)" },
        { label: "Sidebar section nav", ref: "src/pages/DesignSystem2.tsx", note: "Sidebar section nav (10 sections: Text Style, Color Style, Buttons, Icons, Input Fields, Table, Base, Premade, Illustrat" },
    ],
    "tab-button-sidebar-inactive": [
        { label: "Active", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Active (TabButton, sidebar)" },
        { label: "Inactive", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Inactive (TabButton, sidebar)" },
        { label: "Sidebar section nav", ref: "src/pages/DesignSystem2.tsx", note: "Sidebar section nav (10 sections: Text Style, Color Style, Buttons, Icons, Input Fields, Table, Base, Premade, Illustrat" },
    ],
    "tab-toggle": [
        { label: "Redeem / Preset / Percentage / Fix", ref: "src/components/DiscountDialog.tsx", note: "Redeem / Preset / Percentage / Fixed (main dialog tabs)" },
        { label: "Voucher / Points", ref: "src/components/DiscountDialog.tsx", note: "Voucher / Points (redeem-mode sub-tabs)" },
        { label: "Existing Customer / New Customer v", ref: "src/components/CustomerDialog.tsx", note: "Existing Customer / New Customer view toggle" },
        { label: "Dine In / Take Away segmented togg", ref: "src/components/OrderSummaryPanel.tsx", note: "Dine In / Take Away segmented toggle" },
        { label: "Corner radius toggle: None / Sharp", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Corner radius toggle: None / Sharp / Default / Soft / Custom(px)" },
        { label: "Content density toggle: Compact /", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Content density toggle: Compact / Normal / Spacious" },
        { label: "Max width toggle: 5xl / 6xl / 7xl", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Max width toggle: 5xl / 6xl / 7xl / Full" },
        { label: "Preview surface toggle: Card / Fla", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Preview surface toggle: Card / Flat / None" },
        { label: "Sidebar width toggle: Narrow / Def", ref: "src/components/DesignSystem2/DesignSystem2Customizer.tsx", note: "Sidebar width toggle: Narrow / Default / Wide" },
        { label: "Dine In / Take Away", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Dine In / Take Away (TabToggle)" },
        { label: "Preset / Percentage / Fixed", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Preset / Percentage / Fixed (TabToggle)" },
    ],
    "table-action-delete": [
        { label: "Delete", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Delete (TableActionButton, icon-only)" },
    ],
    "table-action-edit": [
        { label: "Edit", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Edit (TableActionButton)" },
    ],
    "table-action-icon": [
        { label: "Open menu", ref: "src/components/DesignSystem2/Premade2.tsx", note: "Open menu (hamburger, Navbar demo)" },
        { label: "More", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "More (TableActionButton, icon-only)" },
        { label: "Previous page", ref: "src/components/DesignSystem2/Table2.tsx", note: "Previous page (chevron-left)" },
        { label: "Next page", ref: "src/components/DesignSystem2/Table2.tsx", note: "Next page (chevron-right)" },
    ],
    "table-action-sort": [
        { label: "Sort", ref: "src/components/DesignSystem2/Buttons2.tsx", note: "Sort (TableActionButton)" },
    ],
};
