/**
 * Button lab — the proposed consolidation plan (curated 2026-07-23).
 *
 * The unified design language: canonical ui/ components + the dialog-system
 * SSOT footer styles + two blessed inline representatives (menu row, list row)
 * are the winners; every other style is assigned to the winner matching its
 * purpose, or retired (dead code / legacy-frozen dialog branches / bespoke
 * widget internals). All 340+ assignments were adversarially reviewed (9-agent
 * pass, 114 corrections applied). Loaded as the lab's default plan when no
 * local plan exists — fully editable there. Regenerate: gen_proposed_plan.py.
 */

export const PROPOSED_PLAN: { blessed: string[]; targets: Record<string, string> } = {
    blessed: [
        "admin-action-primary",
        "admin-action-outline",
        "admin-action-ghost",
        "admin-action-success",
        "admin-action-icon",
        "action-button-primary",
        "action-button-secondary",
        "action-button-outline",
        "inline-inventory-shell-footer-primary",
        "inline-products-configured-dialog-secondary",
        "inline-inventory-shell-footer-danger",
        "inline-inventory-shell-footer-danger-outline",
        "pos-action-default",
        "outline-button",
        "product-card",
        "category-filter-selected",
        "category-filter-unselected",
        "table-action-sort",
        "table-action-icon",
        "table-action-delete",
        "table-action-edit",
        "tab-toggle",
        "tab-button-reports-active",
        "tab-button-reports-inactive",
        "tab-button-sidebar-active",
        "tab-button-sidebar-inactive",
        "numpad-default",
        "numpad-action",
        "numpad-confirm",
        "inline-quicknumpad-keys-white-key",
        "inline-quicknumpad-keys-quick-value",
        "dialog-switch-on",
        "dialog-switch-off",
        "dialog-toggle-row",
        "payment-method-selected",
        "payment-method-unselected",
        "pairing-primary",
        "pairing-secondary",
        "dashed-card-button",
        "inline-customers-sort-menu-item",
        "inline-profitcosts-list-row-btn",
    ],
    targets: {
        "inline-appearances-base-canvas-card": "payment-method-unselected",
        "inline-appearances-color-swatch": "__retire__",
        "inline-appearances-menu-item-card": "product-card",
        "inline-appearances-preview-charge": "__retire__",
        "inline-appearances-preview-ellipsis-icon": "__retire__",
        "inline-appearances-preview-save-order": "pos-action-default",
        "inline-appearances-segmented-control-option": "tab-toggle",
        "inline-assistant-copy-code": "admin-action-icon",
        "inline-assistant-disconnect-chip": "table-action-delete",
        "inline-assistant-example-card": "pos-action-default",
        "inline-assistant-get-pairing-code": "pairing-primary",
        "inline-assistant-new-chat": "admin-action-ghost",
        "inline-assistant-send": "action-button-primary",
        "inline-assistant-unlink-cancel": "admin-action-ghost",
        "inline-assistant-unlink-remove": "inline-inventory-shell-footer-danger",
        "inline-assistant-whatsapp-header-toggle": "admin-action-ghost",
        "inline-cashdraweraudit-export-csv": "admin-action-primary",
        "inline-cashdrawerdialog-legacy-close-x": "admin-action-icon",
        "inline-cashdrawerdialog-legacy-primary": "inline-inventory-shell-footer-primary",
        "inline-cashdrawerdialog-legacy-secondary": "inline-products-configured-dialog-secondary",
        "inline-cashdrawerdialog-shell-primary": "inline-inventory-shell-footer-primary",
        "inline-cashdrawerdialog-shell-secondary": "inline-products-configured-dialog-secondary",
        "inline-cashiertesting-compact-gray": "admin-action-outline",
        "inline-cashiertesting-compact-primary": "admin-action-primary",
        "inline-cashiertesting-danger-row": "inline-inventory-shell-footer-danger",
        "inline-cashiertesting-gray-row-refresh": "admin-action-outline",
        "inline-cashiertesting-gray-row-small": "admin-action-outline",
        "inline-cashiertesting-primary-full-card": "admin-action-primary",
        "inline-cashiertesting-primary-row": "admin-action-primary",
        "inline-cashiertesting-try-again-link": "admin-action-ghost",
        "inline-categories-delete-trash-icon": "table-action-delete",
        "inline-categories-mobile-category-row": "inline-profitcosts-list-row-btn",
        "inline-categoryform-active-status-toggle": "dialog-toggle-row",
        "inline-categoryform-color-swatch": "payment-method-unselected",
        "inline-categoryform-icon-picker": "payment-method-unselected",
        "inline-customerdialog-customer-row": "payment-method-unselected",
        "inline-customerform-active-checkbox-label": "dialog-toggle-row",
        "inline-customers-legacy-dialog-close": "__retire__",
        "inline-customers-legacy-dialog-x": "__retire__",
        "inline-customers-pagination-arrow": "admin-action-icon",
        "inline-customers-pagination-page-number": "category-filter-selected",
        "inline-customers-row-kebab-desktop": "table-action-icon",
        "inline-customers-row-kebab-mobile": "table-action-icon",
        "inline-customers-row-menu-item": "inline-customers-sort-menu-item",
        "inline-custominvoicedialog-add-line-dashed": "dashed-card-button",
        "inline-custominvoicedialog-close-x": "__retire__",
        "inline-custominvoicedialog-payment-method-pill": "payment-method-selected",
        "inline-custominvoicedialog-remove-line-icon": "table-action-delete",
        "inline-custominvoicedialog-submit-legacy": "__retire__",
        "inline-databasereset-blue-autofix": "admin-action-primary",
        "inline-databasereset-gray-manual": "admin-action-outline",
        "inline-databasereset-purple-debug": "admin-action-outline",
        "inline-databasereset-red-reset": "inline-inventory-shell-footer-danger",
        "inline-databasereset-small-refresh": "admin-action-outline",
        "inline-datasetup-clear-red": "inline-inventory-shell-footer-danger",
        "inline-datasetup-populate-blue": "admin-action-primary",
        "inline-deliveryorders-clickable-row": "__retire__",
        "inline-deliveryorders-dialog-close-outline": "inline-products-configured-dialog-secondary",
        "inline-deliveryorders-dialog-close-x": "admin-action-icon",
        "inline-deliveryorders-row-menu-item": "inline-customers-sort-menu-item",
        "inline-deliveryorders-row-menu-item-danger": "table-action-delete",
        "inline-devicepairing-back-to-signin": "admin-action-ghost",
        "inline-devices-copy-code": "pairing-primary",
        "inline-devices-create-cancel-x": "admin-action-icon",
        "inline-devices-create-submit": "pairing-primary",
        "inline-devices-emerald-header-cta": "pairing-primary",
        "inline-devices-issue-new-code": "pairing-secondary",
        "inline-devices-pairing-close-x": "admin-action-icon",
        "inline-devices-revoke": "inline-inventory-shell-footer-danger-outline",
        "inline-devices-secondary-outline": "admin-action-outline",
        "inline-devices-unlock-submit": "admin-action-primary",
        "inline-discountdialog-preset-row": "payment-method-selected",
        "inline-discountdialog-use-maximum": "action-button-outline",
        "inline-electroncashiertesting-test-tile": "pos-action-default",
        "inline-employees-access-level-card-label": "payment-method-unselected",
        "inline-employees-delete-icon-red": "table-action-delete",
        "inline-employees-dropdown-menu-item": "inline-customers-sort-menu-item",
        "inline-employees-dropdown-menu-item-danger": "table-action-delete",
        "inline-employees-edit-icon-blue": "table-action-icon",
        "inline-employees-error-resetdb-red": "inline-inventory-shell-footer-danger",
        "inline-employees-error-retry-blue": "admin-action-primary",
        "inline-employees-fallback-delete-cancel-outline": "inline-products-configured-dialog-secondary",
        "inline-employees-fallback-delete-confirm-red": "inline-inventory-shell-footer-danger",
        "inline-employees-fallback-discard-red": "inline-inventory-shell-footer-danger",
        "inline-employees-fallback-keep-editing-gray": "inline-products-configured-dialog-secondary",
        "inline-employees-icon-disabled": "table-action-edit",
        "inline-employees-kebab-trigger": "table-action-icon",
        "inline-employees-mobile-filter-toggle": "category-filter-unselected",
        "inline-employees-mobile-role-chip": "category-filter-selected",
        "inline-employees-mobile-row-name-button": "inline-profitcosts-list-row-btn",
        "inline-employees-mobile-sheet-close-x": "admin-action-icon",
        "inline-employees-mobile-sheet-save-green": "inline-inventory-shell-footer-primary",
        "inline-employees-operation-dismiss-gray": "admin-action-outline",
        "inline-employees-password-eye-toggle": "admin-action-icon",
        "inline-employees-sync-dismiss-orange": "admin-action-outline",
        "inline-header-dropdown-item-gray": "__retire__",
        "inline-header-logout-cancel": "__retire__",
        "inline-header-logout-confirm": "__retire__",
        "inline-header-notifications-bell": "__retire__",
        "inline-header-sidebar-toggle": "__retire__",
        "inline-header-user-profile-chip": "__retire__",
        "inline-hr-desktop-employee-card": "__retire__",
        "inline-hr-desktop-export": "admin-action-primary",
        "inline-hr-dialog-book-emerald": "inline-inventory-shell-footer-primary",
        "inline-hr-dialog-booking-mode-toggle": "tab-toggle",
        "inline-hr-dialog-calendar-day": "__retire__",
        "inline-hr-dialog-clear": "inline-products-configured-dialog-secondary",
        "inline-hr-dialog-square-icon-slate": "admin-action-icon",
        "inline-hr-dialog-weekday-pill": "category-filter-selected",
        "inline-hr-fallback-save": "inline-inventory-shell-footer-primary",
        "inline-hr-mobile-back-link": "admin-action-ghost",
        "inline-hr-mobile-booking-mode-toggle": "tab-toggle",
        "inline-hr-mobile-calendar-day": "__retire__",
        "inline-hr-mobile-clear-text": "admin-action-ghost",
        "inline-hr-mobile-detail-row": "inline-profitcosts-list-row-btn",
        "inline-hr-mobile-done-slate": "inline-inventory-shell-footer-primary",
        "inline-hr-mobile-edit-details-text": "admin-action-ghost",
        "inline-hr-mobile-employee-row": "inline-profitcosts-list-row-btn",
        "inline-hr-mobile-export-icon": "admin-action-icon",
        "inline-hr-mobile-green-cta-disabled": "admin-action-primary",
        "inline-hr-mobile-green-cta-shadow": "admin-action-primary",
        "inline-hr-mobile-month-picker-chip": "admin-action-icon",
        "inline-hr-mobile-round-icon-slate": "admin-action-icon",
        "inline-hr-mobile-weekday-pill": "category-filter-selected",
        "inline-hr-shell-save-primary": "inline-inventory-shell-footer-primary",
        "inline-imageuploader-dropzone": "dashed-card-button",
        "inline-imageuploader-modal-close": "admin-action-icon",
        "inline-imageuploader-mode-tab": "tab-toggle",
        "inline-imageuploader-overlay-icon": "admin-action-icon",
        "inline-imageuploader-url-apply": "action-button-primary",
        "inline-installbanner-dismiss": "admin-action-icon",
        "inline-installbanner-how": "admin-action-outline",
        "inline-installbanner-install": "admin-action-primary",
        "inline-inventory-header-add-primary": "admin-action-primary",
        "inline-inventory-image-mode-pill-toggle": "tab-toggle",
        "inline-inventory-image-remove-icon": "table-action-delete",
        "inline-inventory-legacy-cancel": "inline-products-configured-dialog-secondary",
        "inline-inventory-legacy-reset-danger-outline": "inline-inventory-shell-footer-danger-outline",
        "inline-inventory-legacy-save-primary": "inline-inventory-shell-footer-primary",
        "inline-inventory-legacy-stockin-green": "inline-inventory-shell-footer-primary",
        "inline-inventory-legacy-stockout-red": "inline-inventory-shell-footer-danger",
        "inline-inventory-row-action-delete": "table-action-delete",
        "inline-inventory-row-action-slate": "table-action-edit",
        "inline-inventory-stock-tab-toggle": "tab-toggle",
        "inline-inventory-upload-dropzone": "dashed-card-button",
        "inline-languageswitcher-header-pill": "admin-action-outline",
        "inline-languageswitcher-sidebar-toggle": "tab-button-sidebar-inactive",
        "inline-layout-mobile-menu-trigger": "admin-action-icon",
        "inline-loginform-back": "__retire__",
        "inline-loginform-employee-card": "__retire__",
        "inline-loginform-keyboard-toggle": "__retire__",
        "inline-loginform-password-eye": "__retire__",
        "inline-loginform-retry": "action-button-primary",
        "inline-loginform-signin": "__retire__",
        "inline-loginform-sync-error-dismiss": "__retire__",
        "inline-loginform2-change-button": "admin-action-ghost",
        "inline-loginform2-numpad-backspace": "numpad-action",
        "inline-loginform2-numpad-key": "numpad-default",
        "inline-loginform2-repair-till": "pairing-primary",
        "inline-loginform2-signin-button": "action-button-primary",
        "inline-loginform2-staff-card": "payment-method-selected",
        "inline-loginform2-sync-dismiss": "admin-action-icon",
        "inline-loginformpwa-back-link": "admin-action-ghost",
        "inline-loginformpwa-sign-in-submit": "action-button-primary",
        "inline-loginformpwa-tenant-row": "inline-profitcosts-list-row-btn",
        "inline-myprofiledialog-applied-footer-primary": "inline-inventory-shell-footer-primary",
        "inline-myprofiledialog-clock-cta": "inline-inventory-shell-footer-primary",
        "inline-myprofiledialog-legacy-close-x": "admin-action-icon",
        "inline-myprofiledialog-legacy-pin-cancel": "inline-products-configured-dialog-secondary",
        "inline-myprofiledialog-legacy-pin-confirm": "inline-inventory-shell-footer-primary",
        "inline-notificationbell-bell": "admin-action-icon",
        "inline-notificationpanel-close-text-button": "admin-action-ghost",
        "inline-notificationsettings-alert-toggle": "dialog-switch-on",
        "inline-notificationsettings-save-button": "admin-action-primary",
        "inline-orderprintbutton-print-order": "admin-action-primary",
        "inline-orderprintmanager-test-print": "admin-action-primary",
        "inline-orderqueue-collected": "pos-action-default",
        "inline-orderqueue-mark-ready": "admin-action-success",
        "inline-orderqueue-open-customer-display": "admin-action-primary",
        "inline-ordersummarypanel-qty-stepper": "__retire__",
        "inline-paymentdialog-quick-action": "action-button-outline",
        "inline-pos-autologout-logout-gray": "inline-inventory-shell-footer-danger",
        "inline-pos-autologout-stay-green-gradient": "inline-inventory-shell-footer-primary",
        "inline-pos-error-retry-blue": "admin-action-primary",
        "inline-pos-error-sync-green": "admin-action-primary",
        "inline-pos-header-menu-icon": "admin-action-icon",
        "inline-pos-statusbar-profile": "admin-action-ghost",
        "inline-pos-sync-banner-dismiss-orange": "admin-action-outline",
        "inline-pos-sync-banner-retry-green": "admin-action-primary",
        "inline-printermanager-complex-icon-remove": "table-action-delete",
        "inline-printermanager-complex-icon-role": "admin-action-icon",
        "inline-printermanager-complex-icon-test": "__retire__",
        "inline-printermanager-complex-modal-cancel": "__retire__",
        "inline-printermanager-complex-modal-setrole": "__retire__",
        "inline-printermanager-complex-role-radio-row": "__retire__",
        "inline-printersetup-close-icon": "admin-action-icon",
        "inline-printersetup-secondary-gray": "inline-products-configured-dialog-secondary",
        "inline-printersetup-tab-pill": "tab-toggle",
        "inline-printertestpage-ds2-primary-action": "admin-action-primary",
        "inline-printertestpage-ds2-secondary-action": "admin-action-outline",
        "inline-printertestpage-tab-btn": "tab-toggle",
        "inline-printerworkflowmanager-ds2-primary": "admin-action-primary",
        "inline-printerworkflowmanager-modal-cancel": "inline-products-configured-dialog-secondary",
        "inline-productassignmentmanager-bulk-action": "admin-action-outline",
        "inline-productassignmentmanager-clear-all-link": "admin-action-ghost",
        "inline-productassignmentmanager-expand-chevron": "admin-action-icon",
        "inline-productassignmentmanager-search-clear": "admin-action-icon",
        "inline-productassignmentmanager-tree-checkbox-row": "dialog-toggle-row",
        "inline-productform-keyboard-toggle": "tab-toggle",
        "inline-productform-status-toggle": "__retire__",
        "inline-productoptionsdialog-close-x": "admin-action-icon",
        "inline-productoptionsdialog-fallback-add": "inline-inventory-shell-footer-primary",
        "inline-productoptionsdialog-fallback-cancel": "__retire__",
        "inline-productoptionsdialog-option-chip": "category-filter-selected",
        "inline-productoptionsdialog-qty-stepper": "inline-quicknumpad-keys-white-key",
        "inline-productoptionsdialog-shell-primary": "inline-inventory-shell-footer-primary",
        "inline-productoptionsdialog-shell-secondary": "inline-products-configured-dialog-secondary",
        "inline-products-legacy-dialog-close": "inline-products-configured-dialog-secondary",
        "inline-products-legacy-dialog-close-x": "admin-action-icon",
        "inline-products-page-next": "admin-action-icon",
        "inline-products-page-number": "category-filter-selected",
        "inline-products-page-prev": "admin-action-icon",
        "inline-products-row-menu-item": "inline-customers-sort-menu-item",
        "inline-products-row-menu-item-danger": "inline-customers-sort-menu-item",
        "inline-products-row-menu-trigger": "table-action-icon",
        "inline-products-row-menu-trigger-sm": "table-action-icon",
        "inline-products-sort-menu-item": "inline-customers-sort-menu-item",
        "inline-productspagereference2-row-kebab": "table-action-icon",
        "inline-productspagereference2-row-menu-delete": "inline-customers-sort-menu-item",
        "inline-productspagereference2-row-menu-item": "inline-customers-sort-menu-item",
        "inline-productspagereference2-sort-menu-item": "inline-customers-sort-menu-item",
        "inline-productspagereference2-toolbar-dropdown-trigger": "admin-action-outline",
        "inline-productwizard-add-outline-wide": "dashed-card-button",
        "inline-productwizard-add-variant-dark": "action-button-primary",
        "inline-productwizard-legacy-close-x": "admin-action-icon",
        "inline-productwizard-row-delete-icon": "table-action-delete",
        "inline-productwizard-row-expand-icon": "admin-action-icon",
        "inline-productwizard-search-result-row": "inline-customers-sort-menu-item",
        "inline-productwizard-stepper-step": "__retire__",
        "inline-profitcosts-add-cost-cta": "admin-action-primary",
        "inline-profitcosts-apply-period-cta": "inline-inventory-shell-footer-primary",
        "inline-profitcosts-back-round-btn": "admin-action-icon",
        "inline-profitcosts-date-preset-chip": "category-filter-selected",
        "inline-profitcosts-delete-charge-btn": "inline-inventory-shell-footer-danger-outline",
        "inline-profitcosts-done-btn": "inline-products-configured-dialog-secondary",
        "inline-profitcosts-freq-segment-desktop": "tab-toggle",
        "inline-profitcosts-frequency-chip-mobile": "category-filter-selected",
        "inline-profitcosts-metric-segment-toggle": "tab-toggle",
        "inline-profitcosts-period-summary-card": "inline-profitcosts-list-row-btn",
        "inline-profitcosts-reset-text-btn": "inline-inventory-shell-footer-danger-outline",
        "inline-profitcosts-round-header-icon-btn": "admin-action-icon",
        "inline-profitcosts-row-trash-btn": "table-action-delete",
        "inline-profitcosts-sheet-close-btn": "admin-action-icon",
        "inline-purchasereceiptimportdialog-add-manual-line": "inline-products-configured-dialog-secondary",
        "inline-purchasereceiptimportdialog-apply-primary": "inline-inventory-shell-footer-primary",
        "inline-purchasereceiptimportdialog-extract-primary": "inline-inventory-shell-footer-primary",
        "inline-purchasereceiptimportdialog-line-delete": "table-action-delete",
        "inline-purchasereceiptimportdialog-scan-tile": "pos-action-default",
        "inline-purchasereceiptimportdialog-upload-tile": "dashed-card-button",
        "inline-purchasereceipts-detail-close": "inline-products-configured-dialog-secondary",
        "inline-purchasereceipts-row-clickable": "__retire__",
        "inline-quicknumpad-legacy-clear-key": "numpad-action",
        "inline-quicknumpad-legacy-quick-value": "inline-quicknumpad-keys-quick-value",
        "inline-quicknumpad-legacy-white-key": "inline-quicknumpad-keys-white-key",
        "inline-receipthistoryselector-receipt-row": "inline-profitcosts-list-row-btn",
        "inline-recipeeditor-add-ingredient": "action-button-primary",
        "inline-recipeeditor-remove-line": "table-action-delete",
        "inline-reports-error-retry": "admin-action-primary",
        "inline-reports-filter-sheet-apply": "inline-inventory-shell-footer-primary",
        "inline-reports-filter-sheet-date-chip": "category-filter-selected",
        "inline-reports-filter-sheet-payment-chip": "payment-method-unselected",
        "inline-reports-filter-sheet-reset": "inline-products-configured-dialog-secondary",
        "inline-reports-mobile-back-chevron": "admin-action-icon",
        "inline-reports-mobile-date-segmented": "tab-toggle",
        "inline-reports-mobile-daterange-summary": "inline-profitcosts-list-row-btn",
        "inline-reports-mobile-explore-nav-row": "inline-profitcosts-list-row-btn",
        "inline-reports-mobile-header-icon": "admin-action-icon",
        "inline-reports-mobile-ranking-row": "inline-profitcosts-list-row-btn",
        "inline-routingdebugger-add-item": "__retire__",
        "inline-routingdebugger-analyze-routing": "admin-action-primary",
        "inline-routingdebugger-remove-item-link": "table-action-delete",
        "inline-routingrulemanager-add-rule": "admin-action-primary",
        "inline-routingrulemanager-delete-icon": "table-action-delete",
        "inline-routingrulemanager-edit-icon": "__retire__",
        "inline-routingrulemanager-modal-save": "inline-inventory-shell-footer-primary",
        "inline-scalesettingspanel-primary-btn": "admin-action-primary",
        "inline-scalesettingspanel-secondary-btn": "admin-action-outline",
        "inline-seedmanagement-clear-trigger": "inline-inventory-shell-footer-danger",
        "inline-seedmanagement-dialog-cancel": "inline-products-configured-dialog-secondary",
        "inline-seedmanagement-dialog-confirm-danger": "inline-inventory-shell-footer-danger",
        "inline-seedmanagement-run-seed": "admin-action-primary",
        "inline-settings-add-voucher": "admin-action-primary",
        "inline-settings-external-check-btn": "admin-action-primary",
        "inline-settings-hardware-tool-card": "payment-method-selected",
        "inline-settings-reset-btn": "inline-inventory-shell-footer-danger-outline",
        "inline-settings-saft-export-btn": "admin-action-primary",
        "inline-settings-save-btn": "admin-action-primary",
        "inline-settings-segmented-option": "tab-toggle",
        "inline-settings-sidebar-tab": "tab-button-sidebar-active",
        "inline-settings-toggle-switch": "dialog-switch-off",
        "inline-settings-vendus-check-btn": "admin-action-outline",
        "inline-settings-voucher-delete": "table-action-delete",
        "inline-sidebar-collapse-toggle": "admin-action-icon",
        "inline-sidebar-logout-button": "admin-action-outline",
        "inline-sidebar-logout-confirm-cancel": "inline-products-configured-dialog-secondary",
        "inline-sidebar-logout-confirm-danger": "inline-inventory-shell-footer-danger",
        "inline-sidebar-nav-link": "tab-button-sidebar-active",
        "inline-sidebar-profile-button": "inline-profitcosts-list-row-btn",
        "inline-tables-add-outline-2xl": "admin-action-outline",
        "inline-tables-banner-park-outline": "admin-action-outline",
        "inline-tables-banner-return-solid": "admin-action-primary",
        "inline-tables-cancel-outline-2xl": "admin-action-outline",
        "inline-tables-dialog-close-x": "admin-action-icon",
        "inline-tables-dialog-destructive-red": "inline-inventory-shell-footer-danger",
        "inline-tables-dialog-discard-textlink": "inline-inventory-shell-footer-danger-outline",
        "inline-tables-dialog-primary-emerald": "inline-inventory-shell-footer-primary",
        "inline-tables-dialog-secondary-outline": "inline-products-configured-dialog-secondary",
        "inline-tables-emerald-cta-2xl": "admin-action-primary",
        "inline-tables-floating-toolbar-icon": "table-action-icon",
        "inline-tables-floor-table": "__retire__",
        "inline-tables-list-row": "inline-profitcosts-list-row-btn",
        "inline-tables-reset-ghost-red": "inline-inventory-shell-footer-danger-outline",
        "inline-transactions-creditnote-cancel": "inline-products-configured-dialog-secondary",
        "inline-transactions-creditnote-confirm": "inline-inventory-shell-footer-danger",
        "inline-transactions-toast-dismiss": "admin-action-icon",
        "inline-virtualkeyboard-action-key": "numpad-action",
        "inline-virtualkeyboard-key": "numpad-default",
        "inline-virtualkeyboard-mode-toggle": "numpad-confirm",
        "inline-virtualnumpad-cancel": "__retire__",
        "inline-weighdialog-add-emerald": "inline-inventory-shell-footer-primary",
        "inline-weighdialog-authorize-slate": "inline-inventory-shell-footer-primary",
        "inline-weighdialog-cancel-outline": "inline-products-configured-dialog-secondary",
        "inline-weighdialog-close-x": "__retire__",
        "inline-weighdialog-retry-amber": "action-button-secondary",
        "pos-action-disabled": "pos-action-default",
        "table-action-icon-pencil": "table-action-edit",
    },
};
