import type { SpecimenInstance } from './buttonLabSpecimens';

/**
 * Real app usage sites of the canonical ui/ components, per specimen key.
 *
 * GENERATED from the post-migration re-extraction (2026-07-23): every
 * <Component .../> call site with its human label. State-twin specimens
 * (selected/unselected, on/off, active/inactive) share their call sites.
 * Regenerate via the re-extraction workflow rather than editing by hand.
 */

export const CANONICAL_INSTANCES: Record<string, SpecimenInstance[]> = {
    "action-button-outline": [
        { label: "Use maximum redeemable points (t('pos.di", ref: "src/components/DiscountDialog.tsx:299" },
    ],
    "action-button-primary": [
        { label: "Process transaction / open payment (t('p", ref: "src/components/OrderSummaryPanel.tsx:360" },
        { label: "Save/Create employee (form submit, no va", ref: "src/pages/Employees.tsx:1214" },
        { label: "Save category \u2014 t('categories.form.creat", ref: "src/components/CategoryForm.tsx:252" },
        { label: "Save customer \u2014 t('customers.form.create", ref: "src/components/CustomerForm.tsx:238" },
        { label: "Confirm payment (t('pos.confirmPayment')", ref: "src/components/PaymentDialog.tsx:189" },
        { label: "Apply discount (t('pos.discountDialog.bu", ref: "src/components/DiscountDialog.tsx:213" },
        { label: "Select customer (t('common.select')) \u2014 c", ref: "src/components/CustomerDialog.tsx:264" },
        { label: "Save new customer (t('pos.customerForm.s", ref: "src/components/CustomerDialog.tsx:285" },
        { label: "Add new customer from empty search state", ref: "src/components/CustomerDialog.tsx:381" },
        { label: "Print receipt (t('common.print'))", ref: "src/components/ReceiptDialog.tsx:85" },
        { label: "Sign in (submit; 'Signing in\u2026' while bus", ref: "src/components/Auth/LoginFormPwa.tsx:69" },
    ],
    "action-button-secondary": [
        { label: "Cancel (employee form BaseDialog footer)", ref: "src/pages/Employees.tsx:1206" },
        { label: "Cancel category form (t('categories.form", ref: "src/components/CategoryForm.tsx:244" },
        { label: "Cancel customer form (t('customers.form.", ref: "src/components/CustomerForm.tsx:231" },
        { label: "Cancel (t('common.cancel')) \u2014 footer", ref: "src/components/DiscountDialog.tsx:206" },
        { label: "Cancel (list view footer)", ref: "src/components/CustomerDialog.tsx:257" },
        { label: "Cancel (add-customer view footer, return", ref: "src/components/CustomerDialog.tsx:278" },
        { label: "Cancel / close receipt preview (t('commo", ref: "src/components/ReceiptDialog.tsx:78" },
    ],
    "admin-action-ghost": [
        { label: "Filters (desktop, no onClick) \u2014 NOTE: cl", ref: "src/pages/Employees.tsx:812" },
        { label: "Try again \u2014 retry loading test history a", ref: "src/pages/CashierTesting.tsx:523" },
        { label: "WhatsApp \u2014 opens the link-WhatsApp panel", ref: "src/pages/Assistant.tsx:78" },
        { label: "New chat (t('assistant.newChat')) \u2014 rese", ref: "src/pages/Assistant.tsx:282" },
        { label: "Change employee (t('login2.changeEmploye", ref: "src/components/Auth/LoginForm2.tsx:529" },
        { label: "\u2190 Back from tenant picker", ref: "src/components/Auth/LoginFormPwa.tsx:94" },
        { label: "Close notification panel", ref: "src/components/notifications/NotificationPanel.tsx:33" },
    ],
    "admin-action-icon": [
        { label: "Close mobile filters sheet (X)", ref: "src/pages/Reports.tsx:391" },
        { label: "Open mobile period picker (SlidersHorizo", ref: "src/pages/ProfitCosts.tsx:440" },
        { label: "Refresh profit data (RefreshCw, mobile h", ref: "src/pages/ProfitCosts.tsx:441" },
        { label: "Back to profit overview (ChevronLeft, op", ref: "src/pages/ProfitCosts.tsx:482" },
        { label: "Back to profit overview (ChevronLeft, pr", ref: "src/pages/ProfitCosts.tsx:492" },
        { label: "Back to profit overview (ChevronLeft, in", ref: "src/pages/ProfitCosts.tsx:501" },
        { label: "Close period picker (X)", ref: "src/pages/ProfitCosts.tsx:508" },
        { label: "Close charge editor (X)", ref: "src/pages/ProfitCosts.tsx:510" },
        { label: "Expand/collapse variant attribute (Chevr", ref: "src/components/ProductWizard.tsx:422" },
        { label: "Edit station (icon Edit, t printerWorkfl", ref: "src/components/PrinterWorkflowManager.tsx:199" },
        { label: "Dismiss sync-degraded banner (X, t('logi", ref: "src/components/Auth/LoginForm2.tsx:394" },
        { label: "Dismiss install banner (X)", ref: "src/components/pwa/InstallBanner.tsx:59" },
    ],
    "admin-action-outline": [
        { label: "Import purchase receipt (t('products.imp", ref: "src/pages/Products.tsx:296" },
        { label: "Toggle sort menu (t('products.header.sor", ref: "src/pages/Products.tsx:305" },
        { label: "Toggle filter menu (t('products.header.f", ref: "src/pages/Products.tsx:341" },
        { label: "Manual Instructions, icon Trash2", ref: "src/components/DatabaseReset.tsx:180" },
        { label: "Debug Info (toggle diagnostics panel), i", ref: "src/components/DatabaseReset.tsx:187" },
        { label: "Toggle filters panel (reports.header.fil", ref: "src/pages/Reports.tsx:402" },
        { label: "Create custom invoice (transactions.cust", ref: "src/pages/Transactions.tsx:648" },
        { label: "Toggle filters (transactions.filters.fil", ref: "src/pages/Transactions.tsx:758" },
        { label: "Refresh transactions (transactions.refre", ref: "src/pages/Transactions.tsx:766" },
        { label: "View receipt (transactions.list.viewRece", ref: "src/pages/Transactions.tsx:947" },
        { label: "Download receipt PDF (transactions.list.", ref: "src/pages/Transactions.tsx:981" },
        { label: "Refresh (profitCosts.header.refresh, des", ref: "src/pages/ProfitCosts.tsx:519" },
        { label: "Reset operating costs to defaults (deskt", ref: "src/pages/ProfitCosts.tsx:660" },
        { label: "Retry after load error (common.retry)", ref: "src/pages/ProfitCosts.tsx:415" },
        { label: "Sort \u2014 toolbar dropdown trigger, t('cust", ref: "src/pages/Customers.tsx:220" },
        { label: "Filter \u2014 toolbar dropdown trigger, t('cu", ref: "src/pages/Customers.tsx:250" },
        { label: "Reset appearance preferences \u2014 t('appear", ref: "src/pages/Appearances.tsx:513" },
        { label: "Show All Devices \u2014 connect to any serial", ref: "src/pages/CashierTesting.tsx:305" },
        { label: "Download (Download icon) \u2014 download ESC/", ref: "src/pages/CashierTesting.tsx:441" },
        { label: "t('printerTest.refreshStatus') (Wifi ico", ref: "src/pages/PrinterTestPage.tsx:218" },
        { label: "Select All (Filtered) Products \u2014 bulk as", ref: "src/components/ProductAssignmentManager.tsx:286" },
        { label: "Clear All Selections \u2014 bulk unassign fro", ref: "src/components/ProductAssignmentManager.tsx:296" },
        { label: "Read scale once (icon RefreshCw, t scale", ref: "src/components/ScaleSettingsPanel.tsx:225" },
        { label: "Park order (active table order banner)", ref: "src/pages/Tables.tsx:729" },
        { label: "Add table (icon Plus, edit-mode toolbar)", ref: "src/pages/Tables.tsx:846" },
        { label: "Cancel (exit edit mode without saving)", ref: "src/pages/Tables.tsx:855" },
        { label: "Sort (ArrowUpDown, toolbar; toolbarBtn c", ref: "src/pages/DeliveryOrders.tsx:379" },
        { label: "Filter (Filter, toolbar; toolbarBtn clas", ref: "src/pages/DeliveryOrders.tsx:413" },
        { label: "Download PDF (Download, fiscal document ", ref: "src/pages/DeliveryOrders.tsx:805" },
        { label: "Open platform (ExternalLink, details dia", ref: "src/pages/DeliveryOrders.tsx:813" },
        { label: "Cycle language (label = language code, e", ref: "src/components/LanguageSwitcher.tsx:66" },
        { label: "How (toggle iOS install steps)", ref: "src/components/pwa/InstallBanner.tsx:51" },
    ],
    "admin-action-primary": [
        { label: "Open customer order-status display (t('o", ref: "src/pages/OrderQueue.tsx:64" },
        { label: "Add product (t('products.header.addProdu", ref: "src/pages/Products.tsx:374" },
        { label: "Edit product CTA in view-product dialog ", ref: "src/pages/Products.tsx:865" },
        { label: "Add category, page header (t('categories", ref: "src/pages/Categories.tsx:121" },
        { label: "Add item, page header (t('inventory.addI", ref: "src/pages/Inventory.tsx:601" },
        { label: "Add voucher \u2014 t('settings.addVoucher'), ", ref: "src/pages/Settings.tsx:1268" },
        { label: "Check external issuer connection \u2014 t('se", ref: "src/pages/Settings.tsx:1909" },
        { label: "Run YAML seeding \u2014 t('seedManagement.run", ref: "src/pages/SeedManagement.tsx:293" },
        { label: "Populate All Data, icon Database, isLoad", ref: "src/components/DataSetup.tsx:149" },
        { label: "Auto-Fix Issues, icon RefreshCw, isLoadi", ref: "src/components/DatabaseReset.tsx:149" },
        { label: "Retry loading report data (reports.error", ref: "src/pages/Reports.tsx:299" },
        { label: "Export Excel (reports.header.exportExcel", ref: "src/pages/Reports.tsx:410" },
        { label: "Export transactions (transactions.header", ref: "src/pages/Transactions.tsx:655" },
        { label: "Segunda via reprint (thermalReceipt.seco", ref: "src/pages/Transactions.tsx:955" },
        { label: "Issue credit note \u2014 className override f", ref: "src/pages/Transactions.tsx:966" },
        { label: "Add operating cost (profitCosts.operatin", ref: "src/pages/ProfitCosts.tsx:486" },
        { label: "Add operating cost (desktop)", ref: "src/pages/ProfitCosts.tsx:668" },
        { label: "Add customer, t('customers.header.addCus", ref: "src/pages/Customers.tsx:279" },
        { label: "Edit customer CTA in view-modal footer, ", ref: "src/pages/Customers.tsx:472" },
        { label: "Retry load, t('employees.errors.retry') ", ref: "src/pages/Employees.tsx:673" },
        { label: "Add employee header CTA (label = isMobil", ref: "src/pages/Employees.tsx:732" },
        { label: "Connect Printer (Usb icon) \u2014 open Web Se", ref: "src/pages/CashierTesting.tsx:298" },
        { label: "Send to Hardware (Send icon) \u2014 send test", ref: "src/pages/CashierTesting.tsx:450" },
        { label: "Connect Hardware / Connecting... (Refres", ref: "src/pages/ElectronCashierTesting.tsx:288" },
        { label: "Hardware Status (CheckCircle icon) \u2014 sho", ref: "src/pages/ElectronCashierTesting.tsx:299" },
        { label: "t('printerTest.setupThermal') (Search ic", ref: "src/pages/PrinterTestPage.tsx:210" },
        { label: "t('printerTest.testPrint') (Printer icon", ref: "src/pages/PrinterTestPage.tsx:226" },
        { label: "Add Station (t printerWorkflow.addStatio", ref: "src/components/PrinterWorkflowManager.tsx:119" },
        { label: "Create First Station (empty-state CTA, t", ref: "src/components/PrinterWorkflowManager.tsx:149" },
        { label: "Save station modal CTA (t printerWorkflo", ref: "src/components/PrinterWorkflowManager.tsx:423" },
        { label: "Add Rule (icon Plus, t printerWorkflow.a", ref: "src/components/RoutingRuleManager.tsx:96" },
        { label: "Start/Stop live weight polling (t scaleS", ref: "src/components/ScaleSettingsPanel.tsx:233" },
        { label: "Detect scale (icon Search, isLoading whi", ref: "src/components/ScaleSettingsPanel.tsx:253" },
        { label: "Edit layout (enter floor-plan edit mode)", ref: "src/pages/Tables.tsx:708" },
        { label: "Return to order (navigate back to /pos)", ref: "src/pages/Tables.tsx:737" },
        { label: "Save (icon Save, opens save-layout confi", ref: "src/pages/Tables.tsx:861" },
        { label: "Retry loading employees (t('login.retry'", ref: "src/components/Auth/LoginForm2.tsx:368" },
        { label: "Save alert settings (Bell icon, isLoadin", ref: "src/components/notifications/NotificationSettings.tsx:294" },
        { label: "Install (PWA native install prompt)", ref: "src/components/pwa/InstallBanner.tsx:43" },
    ],
    "admin-action-success": [
        { label: "Mark queue ticket ready (t('orderQueue.m", ref: "src/pages/OrderQueue.tsx:92" },
        { label: "Mark queue ticket collected (t('orderQue", ref: "src/pages/OrderQueue.tsx:117" },
        { label: "Sync (RefreshCw, toolbar; toolbarBtn cla", ref: "src/pages/DeliveryOrders.tsx:448" },
    ],
    "category-filter-selected": [
        { label: "All Menu category filter (t('pos.allMenu", ref: "src/pages/POS.tsx:723" },
        { label: "Select product category (category.name)", ref: "src/pages/POS.tsx:734" },
    ],
    "category-filter-unselected": [
        { label: "All Menu category filter (t('pos.allMenu", ref: "src/pages/POS.tsx:723" },
        { label: "Select product category (category.name)", ref: "src/pages/POS.tsx:734" },
    ],
    "dashed-card-button": [
        { label: "Add category card, mobile list (t('categ", ref: "src/pages/Categories.tsx:257" },
        { label: "Add category card, desktop grid (t('cate", ref: "src/pages/Categories.tsx:361" },
    ],
    "dialog-switch-off": [
        { label: "Base switch inside local ToggleSwitch wr", ref: "src/pages/Settings.tsx:155" },
        { label: "Auto-lock enable \u2014 t('settings.autoLockT", ref: "src/pages/Settings.tsx:842" },
        { label: "Protect sales in progress \u2014 t('settings.", ref: "src/pages/Settings.tsx:890" },
        { label: "Track inventory (via ToggleSwitch wrappe", ref: "src/pages/Settings.tsx:951" },
        { label: "Allow negative stock (via ToggleSwitch w", ref: "src/pages/Settings.tsx:960" },
        { label: "Auto-clear cart \u2014 t('settings.autoClearA", ref: "src/pages/Settings.tsx:982" },
        { label: "Order ticket queue enable (via ToggleSwi", ref: "src/pages/Settings.tsx:1023" },
        { label: "Loyalty program enable (via ToggleSwitch", ref: "src/pages/Settings.tsx:1116" },
        { label: "Vouchers enable (via ToggleSwitch wrappe", ref: "src/pages/Settings.tsx:1184" },
        { label: "Per-voucher enable \u2014 t('settings.voucher", ref: "src/pages/Settings.tsx:1245" },
        { label: "PIN required for attendance \u2014 t('setting", ref: "src/pages/Settings.tsx:1299" },
        { label: "Compact mode (via ToggleSwitch wrapper)", ref: "src/pages/Settings.tsx:1400" },
        { label: "Show employee photos (via ToggleSwitch w", ref: "src/pages/Settings.tsx:1409" },
        { label: "Fiscal training mode (via ToggleSwitch w", ref: "src/pages/Settings.tsx:1743" },
        { label: "InvoiceXpress finalize-on-issue \u2014 t('set", ref: "src/pages/Settings.tsx:1830" },
        { label: "Auto-email SAF-T to accountant (via Togg", ref: "src/pages/Settings.tsx:2183" },
        { label: "Enable/disable variant attribute", ref: "src/components/ProductWizard.tsx:414" },
        { label: "Enable/disable variant option", ref: "src/components/ProductWizard.tsx:434" },
        { label: "Enable/disable modifier", ref: "src/components/ProductWizard.tsx:483" },
        { label: "Unlimited availability toggle, ingredien", ref: "src/components/ProductWizard.tsx:521" },
        { label: "Large discount alert toggle", ref: "src/components/notifications/NotificationSettings.tsx:201" },
        { label: "Till offline alert toggle", ref: "src/components/notifications/NotificationSettings.tsx:252" },
    ],
    "dialog-switch-on": [
        { label: "Base switch inside local ToggleSwitch wr", ref: "src/pages/Settings.tsx:155" },
        { label: "Auto-lock enable \u2014 t('settings.autoLockT", ref: "src/pages/Settings.tsx:842" },
        { label: "Protect sales in progress \u2014 t('settings.", ref: "src/pages/Settings.tsx:890" },
        { label: "Track inventory (via ToggleSwitch wrappe", ref: "src/pages/Settings.tsx:951" },
        { label: "Allow negative stock (via ToggleSwitch w", ref: "src/pages/Settings.tsx:960" },
        { label: "Auto-clear cart \u2014 t('settings.autoClearA", ref: "src/pages/Settings.tsx:982" },
        { label: "Order ticket queue enable (via ToggleSwi", ref: "src/pages/Settings.tsx:1023" },
        { label: "Loyalty program enable (via ToggleSwitch", ref: "src/pages/Settings.tsx:1116" },
        { label: "Vouchers enable (via ToggleSwitch wrappe", ref: "src/pages/Settings.tsx:1184" },
        { label: "Per-voucher enable \u2014 t('settings.voucher", ref: "src/pages/Settings.tsx:1245" },
        { label: "PIN required for attendance \u2014 t('setting", ref: "src/pages/Settings.tsx:1299" },
        { label: "Compact mode (via ToggleSwitch wrapper)", ref: "src/pages/Settings.tsx:1400" },
        { label: "Show employee photos (via ToggleSwitch w", ref: "src/pages/Settings.tsx:1409" },
        { label: "Fiscal training mode (via ToggleSwitch w", ref: "src/pages/Settings.tsx:1743" },
        { label: "InvoiceXpress finalize-on-issue \u2014 t('set", ref: "src/pages/Settings.tsx:1830" },
        { label: "Auto-email SAF-T to accountant (via Togg", ref: "src/pages/Settings.tsx:2183" },
        { label: "Enable/disable variant attribute", ref: "src/components/ProductWizard.tsx:414" },
        { label: "Enable/disable variant option", ref: "src/components/ProductWizard.tsx:434" },
        { label: "Enable/disable modifier", ref: "src/components/ProductWizard.tsx:483" },
        { label: "Unlimited availability toggle, ingredien", ref: "src/components/ProductWizard.tsx:521" },
        { label: "Large discount alert toggle", ref: "src/components/notifications/NotificationSettings.tsx:201" },
        { label: "Till offline alert toggle", ref: "src/components/notifications/NotificationSettings.tsx:252" },
    ],
    "dialog-toggle-row": [
        { label: "Sell-in-POS toggle (t('inventory.statusL", ref: "src/pages/Inventory.tsx:420" },
        { label: "Item active toggle (t('inventory.activeL", ref: "src/pages/Inventory.tsx:482" },
        { label: "Category active/inactive status toggle", ref: "src/components/CategoryForm.tsx:430" },
        { label: "Customer active toggle (t('customers.for", ref: "src/components/CustomerForm.tsx:378" },
        { label: "Product status toggle, info step (t('pro", ref: "src/components/ProductWizard.tsx:303" },
    ],
    "list-row": [
        { label: "Explore reports nav rows (Employees / Pr", ref: "src/pages/Reports.tsx:367" },
        { label: "Team ranking rows (display-only, no onCl", ref: "src/pages/Reports.tsx:375" },
        { label: "Top products rows (display-only, no onCl", ref: "src/pages/Reports.tsx:381" },
        { label: "Reporting period row \u2014 opens period pick", ref: "src/pages/ProfitCosts.tsx:446" },
        { label: "Table list row \u2014 select/open table (side", ref: "src/pages/Tables.tsx:760" },
        { label: "Tenant membership row \u2014 select workspace", ref: "src/components/Auth/LoginFormPwa.tsx:79" },
        { label: "Receipt history row \u2014 select receipt", ref: "src/components/ReceiptHistorySelector.tsx:101" },
    ],
    "menu-row": [
        { label: "Sort by name ascending (t('products.head", ref: "src/pages/Products.tsx:318" },
        { label: "Sort by name descending (t('products.hea", ref: "src/pages/Products.tsx:327" },
        { label: "View product (t('products.table.view'))", ref: "src/pages/Products.tsx:501" },
        { label: "Edit product (t('products.table.edit'))", ref: "src/pages/Products.tsx:508" },
        { label: "Delete product (t('products.table.delete", ref: "src/pages/Products.tsx:515" },
        { label: "View product, mobile menu (t('products.t", ref: "src/pages/Products.tsx:580" },
        { label: "Edit product, mobile menu (t('products.t", ref: "src/pages/Products.tsx:587" },
        { label: "Delete product, mobile menu (t('products", ref: "src/pages/Products.tsx:594" },
        { label: "View customer, t('customers.table.view')", ref: "src/pages/Customers.tsx:353" },
        { label: "Edit customer, t('customers.table.edit')", ref: "src/pages/Customers.tsx:354" },
        { label: "Delete customer, t('customers.table.dele", ref: "src/pages/Customers.tsx:355" },
        { label: "View customer (mobile menu)", ref: "src/pages/Customers.tsx:401" },
        { label: "Edit customer (mobile menu)", ref: "src/pages/Customers.tsx:402" },
        { label: "Delete customer (mobile menu)", ref: "src/pages/Customers.tsx:403" },
        { label: "Edit employee, t('employees.actions.edit", ref: "src/pages/Employees.tsx:579" },
        { label: "Copy employee number, t('employees.actio", ref: "src/pages/Employees.tsx:588" },
        { label: "Deactivate/reactivate employee (label = ", ref: "src/pages/Employees.tsx:595" },
        { label: "Delete employee, t('employees.actions.de", ref: "src/pages/Employees.tsx:605" },
    ],
    "numpad-action": [
        { label: "PIN pad backspace (Delete icon, aria-lab", ref: "src/components/Auth/LoginForm2.tsx:103" },
    ],
    "numpad-default": [
        { label: "PIN pad digits 1-9", ref: "src/components/Auth/LoginForm2.tsx:94" },
        { label: "PIN pad digit 0", ref: "src/components/Auth/LoginForm2.tsx:96" },
    ],
    "outline-button": [
        { label: "Clear all order lines (t('pos.clearAllOr", ref: "src/components/OrderSummaryPanel.tsx:319" },
    ],
    "pairing-primary": [
        { label: "Pair device (submits pairing code; 'Pair", ref: "src/pages/DevicePairing.tsx:130" },
    ],
    "payment-method-selected": [
        { label: "Select Cash payment method (t('pos.cash'", ref: "src/components/PaymentDialog.tsx:120" },
        { label: "Select Card payment method (t('pos.card'", ref: "src/components/PaymentDialog.tsx:128" },
        { label: "Payment method selector \u2014 .map over ['ca", ref: "src/components/CustomInvoiceDialog.tsx:224" },
    ],
    "payment-method-unselected": [
        { label: "Select Cash payment method (t('pos.cash'", ref: "src/components/PaymentDialog.tsx:120" },
        { label: "Select Card payment method (t('pos.card'", ref: "src/components/PaymentDialog.tsx:128" },
        { label: "Payment method selector \u2014 .map over ['ca", ref: "src/components/CustomInvoiceDialog.tsx:224" },
    ],
    "pos-action-default": [
        { label: "Open cash drawer dialog (t('pos.cashDraw", ref: "src/components/OrderSummaryPanel.tsx:154" },
        { label: "Open employee profile dialog (t('common.", ref: "src/components/OrderSummaryPanel.tsx:161" },
        { label: "Open Tables view (t('pos.tables'))", ref: "src/components/OrderSummaryPanel.tsx:169" },
        { label: "Scan receipt with camera (t('purchaseRec", ref: "src/components/PurchaseReceiptImportDialog.tsx:220" },
    ],
    "product-card": [
        { label: "Product tile \u2014 add product to cart (prod", ref: "src/pages/POS.tsx:844" },
    ],
    "tab-button-reports-active": [
        { label: "Report section tabs (Overview / Employee", ref: "src/pages/Reports.tsx:510" },
    ],
    "tab-button-reports-inactive": [
        { label: "Report section tabs (Overview / Employee", ref: "src/pages/Reports.tsx:510" },
    ],
    "tab-toggle": [
        { label: "Service type toggle: dine-in / take-away", ref: "src/components/OrderSummaryPanel.tsx:188" },
        { label: "Image mode Upload/URL toggle in add/edit", ref: "src/pages/Inventory.tsx:320" },
        { label: "Stock In / Stock Out toggle in update-it", ref: "src/pages/Inventory.tsx:515" },
        { label: "Base segmented control inside local Segm", ref: "src/pages/Settings.tsx:173" },
        { label: "Local AT doc family selector FT/NC (via ", ref: "src/pages/Settings.tsx:1603" },
        { label: "Operating country selector PT/ES (via Se", ref: "src/pages/Settings.tsx:1711" },
        { label: "Fiscal issuer selector (Local AT/Vendus/", ref: "src/pages/Settings.tsx:1727" },
        { label: "InvoiceXpress document type selector (vi", ref: "src/pages/Settings.tsx:1809" },
        { label: "Fiskaly environment selector test/live (", ref: "src/pages/Settings.tsx:1852" },
        { label: "Fiskaly document type selector FT/FS/FR ", ref: "src/pages/Settings.tsx:1862" },
        { label: "Vendus environment selector tests/normal", ref: "src/pages/Settings.tsx:1952" },
        { label: "Mobile date-range preset toggle (Today /", ref: "src/pages/Reports.tsx:336" },
        { label: "Product metric toggle (Profit / Margin /", ref: "src/pages/ProfitCosts.tsx:494" },
        { label: "Operating cost frequency toggle (per des", ref: "src/pages/ProfitCosts.tsx:713" },
        { label: "Booking mode toggle: hr.bookModePeriod /", ref: "src/pages/HR.tsx:532" },
        { label: "Booking mode toggle: hr.bookModePeriod /", ref: "src/pages/HR.tsx:734" },
        { label: "Local SegmentedControl wrapper delegates", ref: "src/pages/Appearances.tsx:175" },
        { label: "via SegmentedControl \u2014 preview tab switc", ref: "src/pages/Appearances.tsx:399" },
        { label: "via SegmentedControl \u2014 content density C", ref: "src/pages/Appearances.tsx:611" },
        { label: "via SegmentedControl \u2014 corner radius pre", ref: "src/pages/Appearances.tsx:619" },
        { label: "via SegmentedControl \u2014 sidebar width Nar", ref: "src/pages/Appearances.tsx:676" },
        { label: "via SegmentedControl \u2014 content max width", ref: "src/pages/Appearances.tsx:684" },
        { label: "via SegmentedControl \u2014 card style Card/F", ref: "src/pages/Appearances.tsx:692" },
        { label: "via SegmentedControl \u2014 neutral scale fam", ref: "src/pages/Appearances.tsx:700" },
        { label: "Printer settings tabs: t('printerTest.ta", ref: "src/pages/PrinterTestPage.tsx:87" },
        { label: "Upload Image / Image URL input-mode togg", ref: "src/components/ImageUploader.tsx:570" },
        { label: "Discount type tabs: Redeem / Preset / Pe", ref: "src/components/DiscountDialog.tsx:226" },
        { label: "Redeem mode tabs: Voucher / Points", ref: "src/components/DiscountDialog.tsx:241" },
        { label: "View toggle: Existing customer / New cus", ref: "src/components/CustomerDialog.tsx:300" },
        { label: "Printer setup source tabs: Network / USB", ref: "src/components/PrinterSetup.tsx:306" },
    ],
    "table-action-delete": [
        { label: "Delete category, mobile list row (Trash2", ref: "src/pages/Categories.tsx:241" },
        { label: "Delete category, desktop grid card (Tras", ref: "src/pages/Categories.tsx:344" },
        { label: "Delete item, mobile card (Trash2, t('inv", ref: "src/pages/Inventory.tsx:669" },
        { label: "Delete item, desktop table (Trash2, t('i", ref: "src/pages/Inventory.tsx:736" },
        { label: "Delete loyalty voucher \u2014 t('settings.vou", ref: "src/pages/Settings.tsx:1250" },
        { label: "Remove operating cost (Trash2)", ref: "src/pages/ProfitCosts.tsx:723" },
        { label: "Delete employee (card footer), t('employ", ref: "src/pages/Employees.tsx:969" },
        { label: "Disconnect (unlink a connected WhatsApp ", ref: "src/pages/Assistant.tsx:115" },
        { label: "Delete variant attribute (Trash2, aria-l", ref: "src/components/ProductWizard.tsx:421" },
        { label: "Delete variant option (Trash2)", ref: "src/components/ProductWizard.tsx:450" },
        { label: "Delete modifier (Trash2)", ref: "src/components/ProductWizard.tsx:499" },
        { label: "Remove ingredient row (Trash2)", ref: "src/components/ProductWizard.tsx:561" },
        { label: "Remove recipe line (Trash2, aria-label t", ref: "src/components/RecipeEditor.tsx:111" },
        { label: "Remove invoice line (aria: t('transactio", ref: "src/components/CustomInvoiceDialog.tsx:177" },
        { label: "Delete purchase line in PurchaseLineEdit", ref: "src/components/PurchaseReceiptImportDialog.tsx:445" },
        { label: "Delete station (icon Trash2, t printerWo", ref: "src/components/PrinterWorkflowManager.tsx:206" },
        { label: "Delete routing rule (icon Trash2, t prin", ref: "src/components/RoutingRuleManager.tsx:154" },
    ],
    "table-action-edit": [
        { label: "Adjust stock, mobile card (SlidersHorizo", ref: "src/pages/Inventory.tsx:655" },
        { label: "Edit item, mobile card (Pencil, t('inven", ref: "src/pages/Inventory.tsx:662" },
        { label: "Adjust stock, desktop table (SlidersHori", ref: "src/pages/Inventory.tsx:722" },
        { label: "Edit item, desktop table (Pencil, t('inv", ref: "src/pages/Inventory.tsx:729" },
    ],
    "table-action-icon": [
        { label: "Row actions kebab, desktop table (MoreVe", ref: "src/pages/Products.tsx:485" },
        { label: "Row actions kebab, mobile card (MoreVert", ref: "src/pages/Products.tsx:569" },
        { label: "Expand/collapse transaction details (Che", ref: "src/pages/Transactions.tsx:874" },
        { label: "Dismiss credit-note success toast (X)", ref: "src/pages/Transactions.tsx:1068" },
        { label: "Row actions kebab (MoreVertical), deskto", ref: "src/pages/Customers.tsx:343" },
        { label: "Row actions kebab (MoreVertical), mobile", ref: "src/pages/Customers.tsx:390" },
        { label: "Employee actions kebab (icon = horizonta", ref: "src/pages/Employees.tsx:572" },
        { label: "Edit employee (card footer), t('employee", ref: "src/pages/Employees.tsx:950" },
        { label: "Edit employee \u2014 disabled lock state, t('", ref: "src/pages/Employees.tsx:958" },
        { label: "Delete employee \u2014 disabled lock state, t", ref: "src/pages/Employees.tsx:976" },
        { label: "Rotate selected table (RotateCw, dark ca", ref: "src/pages/Tables.tsx:897" },
        { label: "Edit selected table (Edit3, dark canvas ", ref: "src/pages/Tables.tsx:898" },
        { label: "Delete selected table (Trash2, dark canv", ref: "src/pages/Tables.tsx:899" },
        { label: "Row actions kebab menu (MoreVertical, pe", ref: "src/pages/DeliveryOrders.tsx:573" },
    ],
};
